### ISSUE TITLE
Motivation for using `MonadBaseControl`?

### ISSUE THREAD

**Issue by ChShersh** [morphismtech/squeal#109]
`MonadBaseControl` is considered a difficult abstraction. When you use `MonadBaseControl`, you can introduce problems to your application without even noticing them at first (especially when your monad stack is non-trivial). See this blog post for reference:

* https://www.fpcomplete.com/blog/2017/06/tale-of-two-brackets

I don't want to say that this a bad typeclass. `MonadBaseControl` is a useful typeclass and has its own place in the world. But I personally would prefer simpler abstractions over complex ones, so I can reason about the code easily.

One of such simpler abstractions is `MonadUnliftIO`:

* http://hackage.haskell.org/package/unliftio-core-0.1.2.0/docs/Control-Monad-IO-Unlift.html#t:MonadUnliftIO

I don't want to promote particular monad stack. I understand that `MonadBaseControl` is more general and allows to work with arbitrary monad transformers like `StateT`. But practice shows that this is rare a good idea and it can lead to problems. 

Would you consider migrating to an alternative approach? Or there's something fundamental that stops `squeal` from dropping `MonadBaseControl`?

**Comment by echatav** [comment]
I'm just more familiar with `MonadBaseControl`. It's greater generality makes it simpler for me to understand.

> But I personally would prefer simpler abstractions over complex ones

I think that in this case simplicity is in the eye of the beholder.

> introduce problems to your application without even noticing them at first

I haven't quite understood this but it seems plausible to me. Whatever my aesthetic preference, preventing bugs is more important.

> Would you consider migrating to an alternative approach?

Sure, and I have considered `MonadUnliftIO `. I listened to Michael Snoyman give a talk on it. He's quite credible about exceptions in Haskell which I don't fully grok. It's not a high priority for me to work on but I'd look favorably at contributed code to refactor the uses of `MonadBase` and `MonadBaseControl` to instead use `MonadIO` and `MonadUnliftIO`.
