### ISSUE TITLE
Foreign reference at the type level

### ISSUE THREAD

**Issue by echatav** [morphismtech/squeal#11]
Right now in Squeal column constraints include `NOT NULL` and `DEFAULT` and are modeled at the type level but foreign keys which in SQL can be either column constraints or table constraints are in Squeal only modeled as table constraints which in turn are only modeled at the value level. This makes it impossible to correctly type `OUTER JOIN`s with `ON` clauses that are reference equalities. For example,

```sql
CREATE TABLE user (
  id serial,
  name text NOT NULL
)
CREATE TABLE file (
  id serial,
  owner REFERENCES user(id),
  content bytea NOT NULL
);
```

```sql
SELECT file.id AS id, user.name AS userName
FROM file LEFT OUTER JOIN user ON (file.owner = user.id)
```

The query above should be typed as `Query Schema '[] '["id" ::: 'Required ('NotNull 'PGint4), "userName" ::: 'Required ('NotNull 'PGtext)` but doing the best Squeal can now do would type `userName` as being `'Null`.

As a first step, we can try adding another branch to the `ColumnType` datakind, perhaps,

```haskell
data ColumnType
  = Optional NullityType
  | Required NullityType
  | References Symbol Symbol NullityType
```

`TypeExpression`s will need a new parameter since they will now be schema dependent. Then a new type expression could be defined and used with type applications.

```haskell
newtype TypeExpression (schema :: TablesType) (ty :: ColumnType)
  = UnsafeTypeExpression { renderTypeExpression :: ByteString }

references
  :: ( HasTable table schema columns
     , HasColumn column columns (optionality ('NotNull ty))
     )
  => TypeExpression schema ('References table column ('NotNull ty))
```

These changes will need to be pushed through in particular for `createTable`.

Once all this has been worked out, outer joins `FromClause`s will need some work to enable reference equalities that will use this information correctly.

**Comment by echatav** [comment]
Actually, no need to add a branch to `ColumnType`. Just add the `schema` parameter to `TypeExpression` and,

```haskell
references
  :: ( HasTable table schema columns
     , HasColumn column columns (optionality ('NotNull ty))
     )
  => TypeExpression schema (Required ('NotNull ty))
```

**Comment by ryantrinkle** [comment]
Awesome!  Note that Optional/Required is orthogonal to References - you can have a nullable column that references another table, which means that it must be valid if it is not null.  That means that the "userName" column actually *inherits* the nullability from file.owner, in this case.

**Comment by echatav** [comment]
Optional/Required is for `DEFAULT` not for `NULL`, badly named? But good to know, thanks, I'll generalize the `references` type expression to accommodate `NULL`s.

**Comment by ryantrinkle** [comment]
Oh, yes, that makes sense, although I'd kind of expect defaultness to be a separate field, since it's orthogonal with everything else.

**Comment by echatav** [comment]
Hmmm, it could be but I fear the proliferation of layers making up the `ColumnType` kind. Maybe I should just let it proliferate and define a bunch of kind synonyms that shorten their names...

**Comment by ryantrinkle** [comment]
Does record syntax work at the type level?  Could maybe make it extensible that way.

**Comment by echatav** [comment]
```haskell
data PGType
data NullType = HasNull | HasNoNull
data DefaultType = HasDefault | HasNoDefault
data ReferenceType = HasReference Symbol Symbol | HasNoReference
data ColumnType = ColumnType (NullType, DefaultType, ReferenceType) PGType
type Unconstrained = '( 'HasNull, 'HasNoDefault, 'HasNoReference)
type NotNull = '( 'HasNoNull, 'HasNoDefault, 'HasNoReference)
type Def = '( 'HasNull, 'HasDefault, 'HasNoReference)
type DefNotNull = '( 'HasNoNull, 'HasDefault, 'HasNoReference)
type References table column = '( 'HasNoNull, 'HasNoDefault, 'References table column)
```

**Comment by ryantrinkle** [comment]
Here's another idea also: the reference doesn't actually have to live in the column - in postgres itself, the reference really lives in the table, and it's really got a type something like `([ColumnNameIn ThisTable], a :: SomeOtherTable, [ColumnNameIn a], MatchingRule)`.  Maybe taking it out of the column would provide some flexibility.  Unique constraints (including PRIMARY KEY, which is really just UNIQUE + NOT NULL) work pretty much the same way.

**Comment by echatav** [comment]
> Does record syntax work at the type level? Could maybe make it extensible that way.

Unfortunately not :-(

There should be an ability to upgrade record selectors to type families (maybe even `Get` and `Modify` type families).

**Comment by echatav** [comment]
> in postgres itself, the reference really lives in the table, and it's really got a type something like ([ColumnNameIn ThisTable], a :: SomeOtherTable, [ColumnNameIn a], MatchingRule)

@ryantrinkle can you point me to some good docs for this?

**Comment by ryantrinkle** [comment]
@echatav Take a look [here](https://www.postgresql.org/docs/current/static/sql-createtable.html), specifically at the part for `FOREIGN KEY`.  The syntax looks like `FOREIGN KEY (a, b, c) REFERENCES some_table (aa, bb, cc)` followed by some optional args.

**Comment by ryantrinkle** [comment]
Note that this is when it's used as a _table constraint_, not a column constraint.

**Comment by echatav** [comment]
Ah yes, I have foreign key table constraints already in Squeal. Adding table constraints to the type system of Squeal is doable too, but it doesn't simplify the problem. Since in Squeal, _some_ column constraints are _already_ at the type level I first thought to see if I could add a foreign key column constraint into the existing system. It also means having a simpler situation to deal with when it propagates into `FromClause`s.

But since I'm contemplating reworking the column constraint system as outlined above anyway, maybe I should add a type level table constraint system. I'll have to think about it.

**Comment by echatav** [comment]
@ryantrinkle 

Can you document here an example with the schema (CREATE statements) with queries and behavior you hope to see?

**Comment by ryantrinkle** [comment]
@echatav I'll take a stab at it, although one snag is that I haven't learned squeal yet! :P

```sql
create table a (id bigserial, id2 bigserial, va text, primary key (id, id2));
create table b (id bigint not null, id2 bigint not null, vb text, constraint fk_b_ a foreign key (id, id2) references a);
select b.id, b.id2, vb, va from b left join a on ((a.id, a.id2) = (b.id, b.id2));
```

Ideally, we could translate this to something returning `(Int64, Int64, Text, Text)`, rather than `(Int64, Int64, Text, Maybe Text)`.  Perhaps the syntax could look something like

```haskell
select (#b ! #id :* #b ! #id2 :* #b ! #vb :* #a ! #va :* Nil) (from (Table #b & LeftJoinForeignKey (#a ! #fk_b_a)))
```

**Comment by echatav** [comment]
Oh I just meant SQL :-) But this helps, thanks.

**Comment by echatav** [comment]
```sql
create table a (id bigserial, id2 bigserial, va text, primary key (id, id2));
create table b (id bigint not null, id2 bigint not null, vb text, foreign key (id, id2) references a(id, id2));
select b.id, b.id2, b.vb, a.va from b left join a on ((a.id, a.id2) = (b.id, b.id2));
```
Hopefully, that's correct PGSQL. Ok, I _think_ that in this case, there's no difference between left and inner join so my temptation is to tell a user to use an inner join instead. But you mentioned there may be a case where there are different results.

**Comment by echatav** [comment]
added in [new version](https://hackage.haskell.org/package/squeal-postgresql-0.2.0.1/docs/Squeal-PostgreSQL-Schema.html#t:TableConstraint)

**Comment by ryantrinkle** [comment]
Awesome!
