### ISSUE TITLE
Transactions within a connection pool

### ISSUE THREAD

**Issue by ilyakooo0** [morphismtech/squeal#111]
I might be doing something wrong, but rapidly calling two functions, which have a `transactionally_` within a `runPoolPQ` yields the following response from Postgres:

```
WARNING: there is no transaction in progress
```

I am not sure what I should provide for context, so I am just going to say that I am writing a Servant app and the warning comes when making two rapid calls to the same path, which modifies different rows in a table in postgres. 

I create the pool like so:

```haskell
createConnectionPool databaseURL 3 0.5 10
```

**Comment by echatav** [comment]
Are you sure it's related to using a connection pool?

I did some searching on the warning. On the plus side, it's only a warning. There's [the answer to this SO question](https://stackoverflow.com/questions/28593685/why-does-this-postgresql-transaction-give-warning-there-is-no-transaction-in-p) which gives some debugging tips.

The [code for `transactionally`](https://github.com/morphismtech/squeal/blob/dev/squeal-postgresql/src/Squeal/PostgreSQL/Transaction.hs#L50) which is what `transactionally_` calls is very simple, just wrapping your action in a begin and commit while rolling back on exceptions.

**Comment by ilyakooo0** [comment]
Well, when this happens, squeal throws an error and the transaction is rolled back. I am assuming that it is related to this warning because there is nothing else abnormal happening.

**Comment by ilyakooo0** [comment]
I think it is related to the handling of the connection pool. I recon that the two consecutive queries get run on the came connection.

This is essentially all of the code that is run:

```haskell
runQ err500 $ updateChannel uId req
```

```haskell
runQ :: ServantErr -> StaticPQ a -> App a
runQ err req = handleSqueal (const $ throwError err) $ asks getPool >>= lift . runPoolPQ req
```

where `App` is a `ReaderT` on `Config`:
```haskell
data Config = Config {
    getPool :: Pool (K Connection Schema)
}
```

All I am doing in the request response handler is calling squeal and I only interact with Postgres with squeal, so I don't think there could have been any other influences on the problem I am encountering.

**Comment by echatav** [comment]
I wonder if something like postgresql-simple's [withTransactionSerializable](http://hackage.haskell.org/package/pg-0.5.2.1/docs/src/Database-PostgreSQL-Simple-Transaction.html#withTransactionSerializable) would help.

**Comment by echatav** [comment]
`squeal throws an error`

What is the exact `SquealException` being thrown?

**Comment by ilyakooo0** [comment]
I'm a little time constrained right now. Will try it and post more detail in a week or two.

**Comment by ilyakooo0** [comment]
The exact error I am getting is:

```haskell
PQException {sqlExecStatus = FatalError, sqlStateCode = Just "40001", sqlErrorMessage = Just "ERROR:  could not serialize access due to concurrent update\n"}
```

I am not sure if this is something the library should have handled or if am screwing up somehow.


I am not sure how I could combine postgresql-simple's `withTransactionSerializable` with a Squeal connection pool since I couldn't find an easy way to extract a postgresql-simple `Connection` object from the connection pool.

**Comment by ilyakooo0** [comment]
Setting the `TransactionMode` to use `ReadCommitted` seems to void the error.

**Comment by echatav** [comment]
> I am not sure how I could combine postgresql-simple's `withTransactionSerializable` with a Squeal connection pool since I couldn't find an easy way to extract a postgresql-simple `Connection` object from the connection pool.

I wasn't suggesting to use it directly but rather noting that maybe Squeal should offer something similar and wondering out loud if it did would using it fix the error. Since Squeal's `transactionally` is similar to postgres-simple's `withTransaction` I reasoned that the latter would likely run into the same problem in a similar situation and that maybe Squeal needs a `transactionallySerializable` or `transactionallyRetry` for that case.

**Comment by echatav** [comment]
Please try using this function and if it fixes your problem I will include it in `Squeal`

```Haskell
transactionallyRetry
  :: (MonadUnliftIO tx, MonadPQ schemas tx)
  => TransactionMode
  -> tx x -- ^ run inside a transaction
  -> tx x
transactionallyRetry mode tx = loop where
  loop = mask $ \restore -> do
    begin mode
    x <- restore $ try tx >>= \case
      Right x' -> return x'
      Left (PQException _ (Just "40001") _) -> loop
      Left err -> rollback >> throwIO err
    commit
    return x
```

**Comment by echatav** [comment]
> Setting the TransactionMode to use ReadCommitted seems to void the error.

Ack, that was the true bug in Squeal since according to the [docs](https://www.postgresql.org/docs/11/transaction-iso.html#XACT-READ-COMMITTED) `ReadCommitted` is the default `IsolationLevel`. I will change `defaultMode` accordingly.
