### ISSUE TITLE
Interval literal support

### ISSUE THREAD

**Issue by arbus** [morphismtech/squeal#113]
Does Squeal support the definition of interval literals? eg:

```sql
SELECT * FROM orders WHERE created_at < NOW() - INTERVAL '7 DAYS'
```

I am currently writing this by defining an `UnsafeExpression`.

I can help write a patch for the library if it is currently not supported but you are open for it.

**Comment by echatav** [comment]
I added affine time operations like your `-` which will be the `!-` operator method of a `TimeOp` class. However I haven't added `NOW()` which I think should be equivalent to `currentTimestamp`. And I haven't added an `INTERVAL` operator. How would you type it? Consider that if it takes a `String` or a `text` `Expression` input then it can easily err if the input is ill-formatted. Or you could go all out and model PostgreSQL's interval [input format](http://www.postgresqltutorial.com/postgresql-interval/). Or you could give it a `DiffTime` input and then format that.

**Comment by arbus** [comment]
I agree on the `-` and `NOW()`.

As for the `INTERVAL` operator, I would suggest that instead of explicitly supporting all the different types of strings that it can represent, we can create a minimal version which would cover most cases and can be combined to form the more complex ones. eg:

```haskell
data Interval = Interval Float IntervalUnit
data IntervalUnit = Year | Month | Week | Day | Hour | Minute | Second
```

```
INTERVAL '1 day' == Interval 1 Day
INTERVAL '1 day ago' == Interval -1 Day
INTERVAL '1 day and 5 hours ago' == Interval -1 Day + INTERVAL -5 Hour
```

**Comment by echatav** [comment]
Great idea! I'll add this and also `now` while I'm at it. How's this look?

```Haskell

data TimeUnit
  = Years | Months | Weeks | Days
  | Hours | Minutes | Seconds
  | Microseconds | Milliseconds
  | Decades | Centuries | Millennia
  deriving (Eq, Ord, Show, Read, Enum, GHC.Generic)
instance RenderSQL TimeUnit where
  renderSQL = \case
    Years -> "years"
    Months -> "months"
    Weeks -> "weeks"
    Days -> "days"
    Hours -> "hours"
    Minutes -> "minutes"
    Seconds -> "seconds"
    Microseconds -> "microseconds"
    Milliseconds -> "milliseconds"
    Decades -> "decades"
    Centuries -> "centuries"
    Millennia -> "millennia"

-- | >>> printSQL $ interval_ 7 Days
-- INTERVAL '7.0 days'
interval_ :: Double -> TimeUnit -> Expr (null 'PGinterval)
interval_ num unit = UnsafeExpression $ "INTERVAL" <+>
  "'" <> fromString (show num) <+> renderSQL unit <> "'"
```

**Comment by arbus** [comment]
Looks good to me!

One thing I'm not too sure about in the SQL construction is how the operator precedence for something like `INTERVAL '1 day'` is handled. It doesn't look like a function, so the same bracketing rules might not apply.

An alternative style that might get us around it:

```
INTERVAL '1 day' == '1 day'::interval
```

I'm just thinking out loud, not sure if the proper operator precedence would be a problem to begin with.

**Comment by echatav** [comment]
Good point. That's why other operators in Squeal are always parenthesized. I'll just do that for intervals too.
