### ISSUE TITLE
How to use IN operator?

### ISSUE THREAD

**Issue by vrom911** [morphismtech/squeal#114]
In PostgreSQL you can make queries in the following way:

```sql
SELECT * FROM users where id IN ('id1', id2');
```

Unfortunately, I don't see how to make it in `squeal`. The closest function I found is [`in_`](https://hackage.haskell.org/package/squeal-postgresql-0.4.0.0/docs/Squeal-PostgreSQL-Query.html#v:in_), but it works with queries, not with the list of the elements.

You can also see how it's done in the `postgresql-simple`:

http://hackage.haskell.org/package/postgresql-simple-0.6.1/docs/Database-PostgreSQL-Simple.html#t:In

**Comment by adfretlink** [comment]
See https://github.com/morphismtech/squeal/issues/74 for the current way of doing an `IN` clause.

**Comment by echatav** [comment]
I simplified it so that in the next version `in_` will just take a list of expressions which is the most common use case. But for now you must use a `values_` query containing your list.
