### ISSUE TITLE
Is there a way to concatenate two `NP` ?

### ISSUE THREAD

**Issue by adfretlink** [morphismtech/squeal#119]
I have a few queries that use the same list of fields, say something like:

```
myFields :: NP (Aliased (Expression Schema (Join SomeVirtualTable a) ('Grouped SomeGrouping) params)) res
  #user ! #emails `as` #userEmail
  #user ! #name `as` #userPhone
```

(The actual list is actually around 15 fields, hence my use of intermediary definition). Splitting it like this is convenient: if I need to express queries that return the same thing but with various conditions, it keeps things DRY.

However, for _one_ particular query, I'd like to add a single field to this list. I have tried cheating my way off with:

```
  select (myFields :* #user ! #otherField `as` otherField)
      -- plus the rest of the query
```

But it obviously do not work, since this is adding an item to an already existing `NP`. I've tried looking at the function and instances of the `NP` datatype, but I didn't really spot something that would allow me to do this.

Is this feasible, and if so, how ?

**Comment by echatav** [comment]
Two ways you can do this. One, you can cons it on the head:

```
select (#user ! #otherField `as` otherField :* myFields)
      -- plus the rest of the query
```

Two, you can define a concatenation operation for `NP` lists using the `Join` type family.

```
(+++) :: NP f xs -> NP f ys -> NP f (Join xs ys)
xs +++ ys = case xs of
  Nil -> ys
  (x :* xs) -> x :* (xs +++ ys)
```

Then as long as inference works out with the `Aliasable` field you can now append it at the end:

```
  select (myFields +++ #user ! #otherField `as` otherField)
      -- plus the rest of the query
```

I should probably add `(+++)` as a utility function perhaps with this name or some other.

**Comment by echatav** [comment]
Also, the next version of Squeal adds an `Also` combinator that allow you to combine `Selection`s.

**Comment by adfretlink** [comment]
Thank you so much. The  `+++` operator is neat indeed, and I think adding it as a utility function is a great idea. Maybe `++*` woul be closer to the list syntax, but `+++` is good too.

I'm still on 0.4.0.0 for now, so no `Also` for me right now. I'll keep it in mind when the release comes out though !

**Comment by echatav** [comment]
new `Additional` type class with `also` method for this
