### ISSUE TITLE
Migration support

### ISSUE THREAD

**Issue by echatav** [morphismtech/squeal#12]
Migration can get quite complicated and I've never had to deal with migration in production, so I would very much appreciate input and help here. Let's suppose that a migration is a sequence of steps, starting with an initial schema, usually empty but not necessarily. Each step consists of running a data definition, or a data manipulation, or doing something in your application. The database itself might be in any intermediate schema according to the migration steps and we want to only run the steps that come after that. Let's sketch.

First, we need an ADT that describes all possible results with details of a migration.

```haskell
data MigrationResult
```

Next we need a GADT describing the steps of a migration.

```haskell
data Migration schema0 schema1 where
  Start :: Migration schema schema
  ThenDo
    :: IO ()
    -> Migration schema schema
  ThenManipulate
    :: Manipulation schema '[] '[]
    -> Migration schema schema
    -> Migration schema schema
  ThenDefine
    :: Definition schema1 schema2
    -> Migration schema0 schema1
    -> Migration schema0 schema2
```

We might also want to have some easy predefined auto-migrations, for things like dropping NOT NULL constraints or anything that can be automatically figured out.

```haskell
class Automigrate schema0 schema1 where
  automigration :: Migration schema0 schema1
```

Finally we'll need to be able to run a migration

```haskell
migrate
  :: MonadBase IO io
  => Migration schema0 schema1
  -> PQ schema0 schema1 io MigrationResult
```

Before we get here, we'll need functionality in Squeal to be able to check the current state of the schema in the database.

**Comment by ludat** [comment]
Hi @echatav , I'd really love this feature

The simplest approach I've seen is the one that rails (active record) uses, it has migrations with timestamps like `2017-01-01-12-45-1234568_Add-column-to-table.rb` and in the database you have a `migrations` table that has stored the migrations that have been run, it seems kind of adhock but it works really well, I've seen it in java and .NET world (flyway and fluid). That way we avoid having to check the database state, and only check if all migrations have been run (although it'd be great to have a function to check if the database matched squeal's schema).

Not sure how to integrate squeal's type safety in there but I think we could get something working.

**Comment by echatav** [comment]
Cool, I looked into Rails Active Record and it looked straight forward. I didn't realize it creates an auxiliary table to track migrations though. Maybe we can write the type for that table using Squeal to start with.

**Comment by legrostdg** [comment]
Another approach is the one used by [diesel](http://diesel.rs/guides/getting-started/), which ASUI doesn't require to add a table for migrations, and uses raw sql for migrations files.

**Comment by ludat** [comment]
@legrostdg AFAIK diesel uses a migrations table as well

**Comment by echatav** [comment]
Added in [new version](https://hackage.haskell.org/package/squeal-postgresql-0.2.0.1/docs/Squeal-PostgreSQL-Migration.html).
