### ISSUE TITLE
Running arbitrary code with the new migration signatures

### ISSUE THREAD

**Issue by adfretlink** [morphismtech/squeal#129]
I had this simple migration:

```
newBussinessStuff :: Migration IO Lame Awesome
newBusinessStuff =
  Migration
    { name = "Add awesome stuff"
    , up = void $ define addAwesomeness
          & pqThen insertSomeSuperCoolData
    , down = void $ define backToLame
    }
```

(To preserve the confidentiality of this proprietary code I replaced actual names with overenthusiastic placeholders). `insertSomeSuperCoolData` was a function that looked like this:

```
insertSomeSuperCoolData :: (MonadBaseControl IO m, MonadPQ Lame m) => m ()
insertSomeSuperCoolData =  traversePrepared_ superCoolManipulation (Only <$> coolData)
```

Since the next release is coming soon (yay !), and since it means a lot of fixes to write, I've decided to start early. The new system for migrations feels more intuitive, since I can get rid of my `void $ define` bits, however I don't see how I can run arbitrary code in-between. So I get something like:

```
newBusinessStuff::  Definition (Public Lame) (Public Awesome)
newBusinessStuff =
  Migration
    { name = "Add awesome stuff"
    , up = addAwesomeness -- no arbitrary code :'(
    , down = backToLame
    }
```

Though I would understand why you'd prevent running arbitrary code in there, I was wondering if you didn't plan some form of espace hatch. I've looked in the code but couldn't find what I was looking for, am I missing or misunderstanding something ?

**Comment by echatav** [comment]
Try this.

```Haskell
newBussinessStuff :: Migration (Terminally PQ IO) Lame Awesome
newBusinessStuff =
  Migration
    { name = "Add awesome stuff"
    , up = terminally $ define addAwesomeness
          & pqThen insertSomeSuperCoolData
    , down = terminally $ define backToLame
    }
```

**Comment by adfretlink** [comment]
Brilliant, it works, thank you so much !

I had actually thought about it when reading `Terminally` in the `Migration.hs` file, but I believed (wrongly, it seems !) that it would break my chain of migrations since I would have had some migration being parametric over `Migration Definition` and others using `Migration (Terminally PQ IO)`. Thanks again !

**Comment by echatav** [comment]
You can convert a `Migration Definition` into a `Migration (Terminally PQ IO)` using `pureMigration`.
