### ISSUE TITLE
Can you clarify the way `SetOfFunction` should be used ?

### ISSUE THREAD

**Issue by adfretlink** [morphismtech/squeal#132]
The current `dev` version has this interesting function:

```
-- | Expand an array to a set of rows
unnest :: SetOfFunction "unnest" (null ('PGvararray ty)) '["unnest" ::: ty]
unnest = unsafeSetOfFunction
```

I had rolled my own in 0.4:

```
unnest
  :: Expression schema from 'Ungrouped params (nullity0 ('PGvararray (nullity1 agg)))
  -> Expression schema from 'Ungrouped params (nullity1 agg)
unnest x = UnsafeExpression $
  "unnest(" <+> renderExpression x <+> ")"
```

I'd love to use the version from the latest version, however I'm not sure I fully understand how to use it. Reading the type `SetOfFunction` I find:

```
type SetOfFunction fun ty setof
  =  forall outer commons schemas params
  .  Expression outer commons 'Ungrouped schemas params '[] ty
     -- ^ input
  -> FromClause outer commons schemas params '[fun ::: setof]
     -- ^ output
```

Which seems to indicate I can't use this as a straight expression. My ideal scenario would be to find the way to use `unnest` in such a context:

```
select_
  (unnest (#q ! #someNameArray) `as` #flagNames
  :* unnest (#q ! #someFlagArray) `as` #flagValues)
(from
  (subquery (someSubquery `as` #q)))
```

However, I don't think there is a way to morph a `FromClause` into an `Expression`. Sure, I could probably find a workaround by using subqueries or stuff like that, but this feels at odds with what native SQL would let me write:

```
select unnest(q.someNameArray) as flagNames, unnest (q.someFlagArray) as flagValues
  (from subquery (someSubquery `as` #q))
```

So is it intentional and users shouldn't use `unnest` (and any `SetOfFunctions`) in the returned fields ? If not, I'll be glad to push a PR offering a version of `unnest` for `Expression`.

I'll gladly admit that I'm having some trouble following some part of the code in the `SetOf` module, so apologies if the answer to my question is actually obvious. I'll also add this is not urgent.

**Comment by echatav** [comment]
`SetOfFunction`s should be used after `from`s. See documentation [here](https://www.postgresql.org/docs/11/functions-srf.html). SQL allows you to use these in your select lists but I'm not sure how to safely allow that in Squeal.

```Haskell
qry :: Query_ schema () (Only (VarArray [Int32]))
qry = select_ (#unnest `as` #fromOnly) (from (unnest (array [1,2])))
```

**Comment by echatav** [comment]
[This article](https://tapoueh.org/blog/2017/10/set-returning-functions-and-postgresql-10/) seems relevant in addressing semantics of possible use in a `Selection`.

> A Set Returning Function is a PostgreSQL Stored Procedure that can be used as a relation: from a single call it returns an entire result set, much like a subquery or a table.

> It used to be possible to use SRF in the SELECT clause, with dubious (but useful at times) semantics, and also in scalar contexts. The semantics have been fixed and are now much clearer, and the uses in scalar contexts are forbidden — they were a hack and never made sense anyway.

**Comment by adfretlink** [comment]
It makes sense indeed. The article is indeed illuminating on the topic. Thank you for your explanations !
