### ISSUE TITLE
Allow `NotNull` expressions where `Null` is the constraint

### ISSUE THREAD

**Issue by ilyakooo0** [morphismtech/squeal#133]
There are several places where the program won't compile because I attempted to pass `NotNull` constrained expressions where the API expected a `Null` expression. 

For example:

```haskell
ifThenElse
    :: Condition schema from grouping params
    -> Expression schema from grouping params ty 
    -> Expression schema from grouping params ty
    -> Expression schema from grouping params ty
```

if the return expression `ty` is intended to be `Null` then it won't compile if I pass a `NotNull` column into either "else" or "then" argument.
This doesn't really make much sense to me. You might want to somehow allow this behaviour.

As a temporary workaround you might want to add something like this:

```haskell
nullify
    :: Expression schema from grouping params ('NotNull ty)
    -> Expression schema from grouping params ('Null ty)
nullify = UnsafeExpression . renderExpression
```

**Comment by echatav** [comment]
Use the notNull function

https://hackage.haskell.org/package/squeal-postgresql-0.4.0.0/docs/Squeal-PostgreSQL-Expression.html#v:notNull
