### ISSUE TITLE
Defining indexes as part of the definition 

### ISSUE THREAD

**Issue by ilyakooo0** [morphismtech/squeal#134]
Although it wouldn't strictly modify the `Definition`, it would be great to be able to specify [Postgres indexes](https://www.postgresql.org/docs/9.1/indexes.html) as part of the schema definition.

**Comment by echatav** [comment]
We need to add `Index` as a constructor for `SchemumType` so that we can track indexes.

**Comment by echatav** [comment]
done in #209
