### ISSUE TITLE
Add comma join syntax with tuples

### ISSUE THREAD

**Issue by ilyakooo0** [morphismtech/squeal#148]
https://www.postgresql.org/docs/9.1/tutorial-join.html

**Comment by echatav** [comment]
You can use `also` to accomplish this.

```Haskell
select Star from (table #foo & also (table #bar))
```

renders as

```SQL
SELECT * FROM "foo", "bar"
```

http://hackage.haskell.org/package/squeal-postgresql-0.5.1.0/docs/Squeal-PostgreSQL-List.html#t:Additional

**Comment by ilyakooo0** [comment]
Oh, nice

sorry, didn't notice it was implemented already
