### ISSUE TITLE
static analysis of .sql files; e.g. detecting implicit string->number conversions

### ISSUE THREAD

**Issue by dckc** [morphismtech/squeal#15]
Squeal is particularly intersting cuz the main project I work on is ~20KLOC of sql. (https://informatics.kumc.edu/work/browser/heron_load ). one of our wishlist level issues is "implicit type conversions". i.e. Oracle will run for 37 hours and then crap out with "illegal number" cuz when it compares a numeric column with a string column, it converts the string to number, and in record 9238749238 out of 238792837927, somebody put "10gal" instead of just "10".

**Comment by echatav** [comment]
In Squeal, an expression comparing a `text` column and a `numeric` column is a compile time error. However, this requires that you write your queries in Squeal not SQL. One day you and I can write a tool that parses SQL and typechecks it with helpful error messages and then charge people $$$ to run it on their legacy SQL :-D

**Comment by dckc** [comment]
yeah...

meanwhile: some quick-n-dirty SQL static analysis in python to generate "what tables are built from what?" diagrams. https://informatics.gpcnetwork.org/trac/Project/ticket/71#comment:2
