### ISSUE TITLE
TypeExpression from Hask

### ISSUE THREAD

**Issue by ilyakooo0** [morphismtech/squeal#150]
Something like this

```haskell
hask :: forall h null schemas . TypeExpression schemas (null (PG h))
```

so that it could be used like so:

```haskell
notNullable (hask @Text) `as` #foo
```

**Comment by ilyakooo0** [comment]
It might be even more awesome if we could somehow specify nullity through type application, but I can think of an elegant way from the top of my head.

**Comment by echatav** [comment]
You could do this for some types that have `PGTyped` instances. It might be nice. You can also get the nullity of a Haskell type by using `NullPG` instead of `PG`. A PR would be welcome.
