### ISSUE TITLE
Some migrations downgrade cannot be written

### ISSUE THREAD

**Issue by adfretlink** [morphismtech/squeal#152]
I might be wrong on this, but it seems that the way the `addConstraint` and `addColumn` work makes it impossible to reverse the deletion of constraint or columns that are not last in their list.

E.g.: if you have a list of 2 constraints on a table, and a migration to remove the first one, it seems impossible to write the `down` migration; the recreating of the constraint will put it _last_ on the list of constraints. (Same for columns, obviously). This can be mitigated using an `UnsafeManipulation`, of course, but it's not very user-friendly nonetheless.

**Comment by echatav** [comment]
Yes, I was thinking about this. Unfortunately Postgres doesn't support column re-ordering which is what would make `ADD COLUMN` invertible. I'm not sure how to fix this because it's a limitation of Postgres. Constraint order is less of an issue since the order of constraints is not referenced anywhere. Column order matters to things like `SELECT *` but constraint order doesn't. So you can define a type family which checks that two type level lists are permutations of one another and use it to make a constraint reordering definition.

```Haskell
reorderConstraints
  :: ( Has sch db schema
     , Has tab sch (Table (constraints0 :=> columns)
     , IsPerm constraints0 constraints1 )
  => QualifiedAlias sch tab
  => Definition db (Alter sch (Alter tab ('Table (constraints1 :=> columns) schema) db)
reorderConstraints = UnsafeDefinition ";"
```

I'm open to suggestions for how to solve the column reordering conundrum.

**Comment by echatav** [comment]
See https://wiki.postgresql.org/wiki/Alter_column_position

**Comment by adfretlink** [comment]
I think that column reordering is a problem that cannot be fixed for the time being - I thought hard about it and couldn't find a way to solve it. Maybe Postgres will provide us with a solution for this in a future version, but in the meantime, I don't think there is a way to fix this.

That might mean there should be a way to opt out of a `downgrade` on a migration, though. (Which doesn't seem too shocking when it comes to droping columns - it's frequent to incur a irreversible data loss in such situations, and a downgrade doesn't make much sense in such instances ?).

The `reorderConstraints` would make for a great addition - in my experience, dropping constraints (often because you need to change them) is way more frequent than dropping columns.

**Comment by adfretlink** [comment]
(Of course, we could also discontinue support for `SELECT *`, but that might be a tad drastic. You'd get my support on this, though :grin: )

**Comment by echatav** [comment]
We _could_ add the option of one-way migrations. I imagine just a module replicating the current invertible migrations but with `down`, `migrateDown` and `MigrateDown` removed. It feels ugly to me, but honestly the project I'm working on just ignores all the `down`s anyway.

Here's a fancy idea. Make migrations one-way, but have `Migratory` instances for 4 types, `Definition`, and `Terminally PQ IO` as well as `Ambi Definition` and `Ambi (Terminally PQ IO)` with.

```Haskell
newtype Ambi c x y = Ambi
  { up :: c x y
  , down :: c y x
  }
```

**Comment by echatav** [comment]
It was easier than I thought to add support for one way migrations! #153

**Comment by adfretlink** [comment]
I've seen your PR, it's both eloquent and elegant ! Thank you very much !
