### ISSUE TITLE
How does this package compare to other packages compatible with PostgreSQL ?

### ISSUE THREAD

**Issue by flip111** [morphismtech/squeal#16]
What's "deep embedding" in this context?

Here are a bunch of other libraries to compare with
https://hackage.haskell.org/package/persistent-postgresql
https://hackage.haskell.org/package/hasql
https://hackage.haskell.org/package/opaleye
https://hackage.haskell.org/package/postgresql-simple

Perhaps some information can be added to the readme later on.

**Comment by echatav** [comment]
For a set of views, which is not to say definitions, and general discussion of what a "deep embedding" means see [this post](http://composition.al/blog/2015/06/02/embedding-deep-and-shallow/).

For Squeal specifically, I meant essentially an embedding of SQL including DML and DDL into Haskell, but not just the term language of SQL at the term level in Haskell, but also the type level of SQL at the type level in Haskell.

I wrote about all of the libraries you linked and more in the [announcement](https://www.morphism.tech/announcing-squeal/) for Squeal. I don't really consider it appropriate for me as one of the library authors to drill down into specific feature comparisons. But, I am very happy to answer questions about Squeal.

**Comment by flip111** [comment]
> I don't really consider it appropriate for me as one of the library authors to drill down into specific feature comparisons.

Up to you of course, but from my point of view it would be an expert opinion and very welcome.

I heard only beam and postgresql-orm can do associations and aggregates. It's something i wouldn't want to do be inventing myself, does squeal have it?

Perhaps the two links you gave can be put in the readme? People just land on the github page not knowing it's there.

I don't have any further (urgent) questions at this point so i'm closing the issue for the moment.

**Comment by echatav** [comment]
We can leave this open as a reminder to me to put more useful info in the README. Thanks!

> I heard only beam and postgresql-orm can do associations and aggregates. It's something i wouldn't want to do be inventing myself, does squeal have it?

Squeal has typesafe aggregation. The problem with creating typesafe aggregation is knowing which columns are being grouped and which are not as those that are grouped can be called without an aggregate function applied. In Squeal, the grouping structure of the query is retained at the type level. Here's an example of an aggregate query in Squeal and its corresponding SQL:

```haskell
select (sum_ #col2 `As` #sum :* #col1 `As` #col1 :* Nil)
    ( from (Table (#tab `As` #table1))
      & group (By #col1 :* Nil) 
      & having (#col1 + sum_ #col2 .> 1) )
```
```sql
SELECT sum(col2) AS sum, col1 AS col1
    FROM tab AS table1
      GROUP BY col1
      HAVING ((col1 + sum(col2)) > 1)"
```
I think by "associations" what's probably meant is type safe joins across foreign key references. Here Squeal probably does an ok job but not perfect. Squeal definitely offers all the joins in PostgreSQL like CROSS, INNER and LEFT and RIGHT and FULL OUTER joins. Here's an example of an INNER JOIN in Squeal.
```haskell
select
    ( #o ! #price `As` #order_price :*
      #c ! #name `As` #customer_name :*
      #s ! #name `As` #shipper_name :* Nil )
    ( from (Table (#orders `As` #o)
      & InnerJoin (Table (#customers `As` #c))
        (#o ! #customer_id .== #c ! #id)
      & InnerJoin (Table (#shippers `As` #s))
        (#o ! #shipper_id .== #s ! #id)) )
```
Squeal also supports declaring foreign key references in create statements. For example,
```haskell
createTable #users
    ( serial `As` #id :*
      (text & notNull) `As` #name :* Nil )
    [ primaryKey (Column #id :* Nil) ]
  >>>
  createTable #emails
    ( serial `As` #id :*
      (int & notNull) `As` #user_id :*
      text `As` #email :* Nil )
    [ primaryKey (Column #id :* Nil)
    , foreignKey (Column #user_id :* Nil) #users (Column #id :* Nil)
      OnDeleteCascade OnUpdateCascade ]
```
However, Squeal does not currently embed the foreign key references at the type level. Thus, even though in principle outer joins across foreign keys can be statically known to be NOT NULL, Squeal does not currently offer the facility to propagate that constraint. #11 and #14 are tracking progress on adding this capability.

**Comment by echatav** [comment]
Added more explanatory material in README and a features list.
