### ISSUE TITLE
In the README, the haskell data model not consistent with the database schema

### ISSUE THREAD

**Issue by hughjfchen** [morphismtech/squeal#164]
In the database schema definition, there're two tables, user and email, but in the following haskell data model, there is only one user record. Isn't it supposed there should be two haskell records, user and email according to the database schema definition?

**Comment by echatav** [comment]
There is no requirement in Squeal that your Haskell data model matches your Postgres schema. This gives users the freedom to define their schema however they like, from fully normalized to fully denormalized and anything in between. Squeal attempts to offer a separation of concerns where applicable.

**Comment by hughjfchen** [comment]
> Squeal attempts to offer a separation of concerns where applicable.
Wow, glad to know about that. I've been searching for months in haskell ecosystem for this. Really appreciate for this library setting the goal to separate haskell data model with the database schema. 
As I've gone through the doc and sample, I do notice that some haskell data would add some database related type constraints. For example, the code within the `example.hs`:
`data User = User { userName :: Text, userEmail :: Maybe Text, userVec :: VarArray (Vector (Maybe Int16)) }
  deriving (Show, GHC.Generic)
instance SOP.Generic User
instance SOP.HasDatatypeInfo User

users :: [User]
users =
  [ User "Alice" (Just "alice@gmail.com") (VarArray [Nothing, Just 1])
  , User "Bob" Nothing (VarArray [Just 2, Nothing])
  , User "Carole" (Just "carole@hotmail.com") (VarArray [Just 3])
  ]`
Does it mean that the haskell data can't separated completely with the database schema?

**Comment by hughjfchen** [comment]
So we can still separate the DB related instances definitions from the haskell data model? If yes, that still a good thing.

**Comment by echatav** [comment]
yes

**Comment by hughjfchen** [comment]
Thanks for your clarification. And is this also related to the issue #175 ?

**Comment by echatav** [comment]
Yes, these things aren't about unifying Haskell and Postgres user data models but about unifying Haskell and Postgres [datatypes](https://www.postgresql.org/docs/12/datatype.html).

**Comment by hughjfchen** [comment]
Thank you @echatav , I think my question had been answered very clearly, so I'll close it. Thanks again.
