### ISSUE TITLE
Should Haskell record field names have to match Postgres column names?

### ISSUE THREAD

**Issue by echatav** [morphismtech/squeal#166]
We could generalize the class of Haskell types that are decodable from rows `FromRow row hask` from only record types whose field names match the column names to any product type whose factors are the the same order as the columns. Then you can decode your query results to tuples or records which don't have exactly the same names (useful because Haskell records often have a different naming convention than Postgres columns). The downside would be that the matching requirement enforced a certain kind of code legibility which would be lost.

**Comment by ilyakooo0** [comment]
I think explicitly specifying how field names are converted is not necessarily a bad thing.

What I think could be very useful is providing a way to have a tuple as a result of a query. (Not necessarily exporting the ability to implement it for custom types.)

An idea could be to have a type class which provides a name mapping for a specific record-table pair (roughly speaking)
