### ISSUE TITLE
char and varchar conversion

### ISSUE THREAD

**Issue by ilyakooo0** [morphismtech/squeal#176]
It should probably be possible to convert `Text` and `String` to and from `char` and `varchar`.

**Comment by echatav** [comment]
Is [`cast`](https://hackage.haskell.org/package/squeal-postgresql-0.5.1.0/docs/Squeal-PostgreSQL-Expression-Type.html#v:cast) sufficient?

**Comment by ilyakooo0** [comment]
yes, for my purposes it is. 

but it might be useful to have `ToParam` and `FromValue` instances.

**Comment by echatav** [comment]
I'm hesitant about those instances because the static sizes just don't match up with `String` or `Text`.

**Comment by ilyakooo0** [comment]
I agree.

I am not sure if this would be overkill, but I think supplying a `newtype` wrapper and smart constructors (it should check that the string actually fits into the column) for these types might be useful.

**Comment by echatav** [comment]
I'd be open to a PR
