### ISSUE TITLE
Select without from

### ISSUE THREAD

**Issue by ilyakooo0** [morphismtech/squeal#178]
It would be great to be able to query for example an existence of an entry without resorting to hacks such as selecting from a table without referencing its columns, or selecting true where condition.

**Comment by echatav** [comment]
Does [`exists`](https://hackage.haskell.org/package/squeal-postgresql-0.5.1.0/docs/Squeal-PostgreSQL-Expression-Subquery.html#v:exists) help?

**Comment by ilyakooo0** [comment]
Not really because to turn it into a query, I have to use `select`, which requires me to specify a table.

**Comment by echatav** [comment]
Does [`values` or `values_`](https://hackage.haskell.org/package/squeal-postgresql-0.5.1.0/docs/Squeal-PostgreSQL-Query.html#v:values) help? If not, what's an example SQL query you're unable to replicate?

**Comment by ilyakooo0** [comment]
it looks like `values` might be a solution (didn't really look into it though)

in broad strokes what I am trying to do is have something like this

```haskell
userExists = select (exists (select Star (from #users) & where_ (#email .== param @1))
```

**Comment by echatav** [comment]
I'd do something like
```Haskell
userQ :: Query_ DB (Only Text) (Only Int64)
userQ = select (1 `as` fromOnly) (from (table #users) & where_ (#email .== param @1)

userExists :: MonadPQ DB pq => Text -> pq Bool
userExists email = isJust <$> (firstRow =<< runQueryParams userQ (Only email))
```

**Comment by ilyakooo0** [comment]
Yes, this is *a* way. But I think we can do better :)

I feel like adding an "empty" phantom `FromClause` or `TableExpression` (which doesn't bring any new columns into scope) might be a good solution.

**Comment by echatav** [comment]
> in broad strokes what I am trying to do is something similar to this:
> `userExists = select (exists (select Star (from (table #users)) & where_ (#email .== param @1)))`

I think the solution to this is to use `values_` along with `exists`.
