### ISSUE TITLE
exists returns nullable

### ISSUE THREAD

**Issue by ilyakooo0** [morphismtech/squeal#180]
`exists` currently returns an `Expression` of type `Null PGbool`. I feel like it should be `NotNull PGbool`. I might be wring, but I'm pretty sure there isn't a case where it returns null.

**Comment by echatav** [comment]
In order to use it in places where you want a `Condition`. Rather than being `Null PGbool`, you can make it polymorphic as `null PGbool`, so it can be used as a `Condition` or also as a not null boolean.
