### ISSUE TITLE
Returning Manipulation freezes runtime

### ISSUE THREAD

**Issue by tuomohopia** [morphismtech/squeal#184]
I'm seeing my app completely freeze when trying to extract values with `getRow 0` or `firstRow`
from a returning `InsertInto` manipulation.

On top of freezing, something seems to lock the executable on the filesystem even after manual termination of the process. Fails on both WIN10 as well as Ubuntu (Travis).

For example a manipulation like this:
```haskell
createUser :: Manipulation_ Schemas InsertUser (APIUser_ Identity)
createUser = insertInto
    #users
    (Values_
        (    Default
        `as` #id
        :*   Set (param @1)
        `as` #email
        :*   Set (param @2)
        `as` #password
        :*   Set (param @3)
        `as` #first_name
        :*   Set (param @4)
        `as` #gender
        :*   Set (param @5 & cast int2)
        `as` #birthyear
        :*   Set (param @6)
        `as` #inserted_at
        :*   Set (param @6)
        `as` #updated_at
        )
    )
    OnConflictDoRaise
    (Returning_
        (    #email
        `as` #email
        :*   #first_name
        `as` #first_name
        :*   #gender
        `as` #gender
        :*   #birthyear
        `as` #birthyear
        )
    )
```
where `APIUser_` is a simple Higher Kinded Data type:
```haskell
data APIUser_ p = APIUser_ {
    email :: HKD p Email
    , first_name :: HKD p FirstName
    , gender :: HKD p (Maybe Gender)
    , birthyear :: HKD p Birthyear
} deriving (GHC.Generic)
instance SOP.Generic (APIUser_ Identity)
instance SOP.HasDatatypeInfo (APIUser_ Identity)

type family HKD f a where
    HKD Identity a = a
    HKD f        a = f a
```

Then, when trying to do this, the whole app freezes:
```haskell
createUserSession
    :: (MonadPQ Schemas m, MonadIO m) => InsertUser -> m (APIUser_ Identity)
createUserSession user = getRow 0 =<< manipulateParams createUser user
```

I've tried multiple ways of connection pooling, hitting the same issue.

Some things I noticed:
* `ntuples` won't freeze, prints `Row 1`
* `ExecStatus` is `TuplesOK`, indicating there was no problems with the query
* Database has the inserted record

**Comment by tuomohopia** [comment]
`getRow 1` expectedly throws an exception for index out of bounds.

I'm running:
* Postgres 11
* GHC 8.6.5
* `lts-14.12`

**Comment by echatav** [comment]
Hmmm, that's strange. Not sure why it would freeze like that. My only guess is it has something to do with the type family? Have you tried just using a normal non-higher-kinded datatype to isolate if that's an issue?

* Unrelatedly, no need to write ``#email `as` #email``; Just `#email` is fine.

**Comment by tuomohopia** [comment]
@echatav I just tried:
```haskell
data RowUser = RowUser {
    rowEmail :: Email
    , rowFirstName :: FirstName
    , rowGender :: Maybe Gender
    , rowBirthyear :: Birthyear
} deriving (GHC.Generic, Show, Eq)
instance SOP.Generic RowUser
instance SOP.HasDatatypeInfo RowUser
```
So it turns out my `Gender` type was causing the problem:

```
data Gender = Male | Female | Other
    deriving (Show, Read, Eq, Generic)

instance ToJSON Gender
instance FromJSON Gender
type instance PG Gender = 'PGtext
instance SOP.Generic Gender
instance SOP.HasDatatypeInfo Gender

instance ToParam Gender 'PGtext where
    toParam = K . Encoding.text_strict . Strict.Text.pack . show

instance FromValue 'PGtext Gender where
    fromValue = fromValue @ 'PGtext
```

Am I doing something obviously wrong here? Removing this field/column from the return type seems to make it work again.

**Comment by echatav** [comment]
With an enum like that you _could_ create a corresponding PG enum type. But if you'd like to store it as text then I might do the instances like so:

```Haskell
type instance PG Gender = 'PGtext
instance ToParam Gender 'PGtext where
  toParam = toParam @String @'PGtext . show
instance FromValue 'PGtext Gender where
  fromValue = do
    str <- fromValue @'PGtext @String
    case readMaybe str of
      Just val -> return val
      Nothing -> throwError $ "unexpected gender: " <> Strict.Text.pack str
```

**Comment by tuomohopia** [comment]
Thank you again! defining that `fromValue :: Value Gender` was indeed the problem. It just silently failed and jammed everything.

Thanks for the example solution too, I can now leverage it with my other sum types!

**Comment by tuomohopia** [comment]
Going back to this, how would it work if it was an enum type instead?

I'm trying like this:
```haskell
type Schema
    = '["users" ::: UsersTable, ..., "gender" ::: 'Typedef (PG (Enumerated Gender))]

type Schemas = '["public" ::: Schema]
```

then when wrapping
```haskell
import qualified Squeal.PostgreSQL             as S
import qualified Squeal.PostgreSQL.Pool        as SPG

type SquealPool = SPG.Pool (S.K S.Connection Schemas
)
newtype AppT m a
    = AppT
    { runApp :: ReaderT SquealPool (ExceptT ServerError m) a
    } deriving
    ( Functor, Applicative, Monad, MonadReader SquealPool, MonadError ServerError
    , MonadIO
    )
```

I'm getting an error at `MonadReader SquealPool`:
```
* Illegal type synonym family application in instance: SquealPool
* In the newtype declaration for `AppT'

```

**Comment by echatav** [comment]
The error is telling you that GHC has a rather annoying limitation; you cannot use type synonym family application in an instance. The easiest way to fix that in your case would be to make `SquealPool` a `newtype`.

**Comment by tuomohopia** [comment]
I see. I think I got around it with your tip of just using `newtype`.  🙏
