### ISSUE TITLE
Upgrade to GHC 8.8.2 / lts-15.0

### ISSUE THREAD

**Issue by tuomohopia** [morphismtech/squeal#193]
I bumped the resolver at `stack.yaml` to `lts-15.0`, which is GHC 8.8.2. I'm now getting the following error:
```
In the dependencies for squeal-postgresql-0.5.2.0:
Error: While constructing the build plan, the following exceptions were encountered:

    generics-sop-0.5.0.0 from stack configuration does not match >=0.3.2.0 && <0.5.0.0  (latest matching version is 0.4.0.1)
needed due to project-api-0.1.0.0 -> squeal-postgresql-0.5.2.0
```

Does this mean that the latest version of `squeal-postgresql` is incompatible with the latest `lts-15.0` for now, because `lts-15.0` comes with `generics-sop` 0.5.0.0 while `squeal-postgresql` requires it to be <0.5.0.0 ?

**Comment by echatav** [comment]
The latest released version of squeal is incompatible with generics-sop-0.5 but the development branch has been hacked with CPP to be compatible with both generics-sop-0.5 and <= 0.5.

**Comment by echatav** [comment]
https://github.com/morphismtech/squeal/blob/4690fcbff2251dbe0db43565305861cea3691215/squeal-postgresql/src/Squeal/PostgreSQL/PG.hs#L257

**Comment by tuomohopia** [comment]
Got it, I'll try using the dev branch instead if I need to migrate to `lts-15.0` soon.

**Comment by echatav** [comment]
You can also override the choice of generics-sop in your stack yaml file. Dev is under active development.

**Comment by tuomohopia** [comment]
Basically using `lts-15.0` but keeping `generics-sop` version at < 0.5 for Squeal? That's actually the best choice yep.

**Comment by tuomohopia** [comment]
Coming back to this now that we're at `lts-15.4` and `GHC 8.8.3`; downgrading `generics-sop` leads to a world of problems on my end. It requires downgrading `sop-core` & `template-haskell` and these propagate to eventually requiring a lower `base` version.

Any idea yet when a new version compatible with `GHC 8.8.X` will be surfacing? In terms of successful compiling, the only problem is the `generics-sop` version constraint as far as I can tell.

**Comment by echatav** [comment]
I'm going to _try_ to make the next version compatible with `lts-14.2` and `lts-15.4`.

Some things I'll have to figure out.
* `time` dependency; `>= 1.9' has the very convenient `Data.Time.Format.ISO8601` module.
* `generics-sop` dependency; CPP has made this cross-compatible
* `with-utf8` dependency; used to fix bug in hedgehog property tests; not on stackage

Figuring out this dependency stuff confuses me a little. I'm pretty bad at versioning and never really understood PVP or all these things people talk about. Having hackage & stackage just adds to my confusion but I've muddled through before. It's the next thing on my agenda to figure out on the way to `squeal-postgresql-0.6`.

**Comment by tuomohopia** [comment]
Yeah don't mean to push you, unfortunately I don't understand a thing about versioning/deps in Haskell myself. 

I'm currently running on `lts-14.3` without any problems, just adding `- squeal-postgresql-0.5.2.0` to `extra-deps` in `stack.yaml` gets it working.
