### ISSUE TITLE
Question: Extending timestamps to all tables

### ISSUE THREAD

**Issue by tuomohopia** [morphismtech/squeal#196]
I find myself repeating this pattern for timestamps in every table in my schema:
```haskell
type Columns = '[
  -- ...
  , "inserted_at" ::: 'NoDef :=> 'NotNull 'PGtimestamptz
  , "updated_at" ::: 'NoDef :=> 'NotNull 'PGtimestamptz
  ] 
```

And then likewise in the `setup :: Definition ...`:
```haskell
    createTable
          #tableName
          (    
         -- ...
          :*   (timestampWithTimeZone & notNullable)
          `as` #inserted_at
          :*   (timestampWithTimeZone & notNullable)
          `as` #updated_at
          ) (...)

```

As I'm not fluent in type level programming I've been struggling to find a way to abstract this pattern into something composable. 

Are there any good ways of producing something of higher order than encapsulates this into each of my table schema spec & migrations?

**Comment by echatav** [comment]
There's lots of ways of doing this. You could define

```Haskell
type MetaColumns = '[
  "inserted_at" ::: 'NoDef :=> 'NotNull 'PGtimestamptz,
  "updated_at" ::: 'NoDef :=> 'NotNull 'PGtimestamptz]

metaColumns :: NP (ColumnTypeExpression db) MetaColumns
metaColumns =
  (timestampWithTimeZone & notNullable) `as` #inserted_at :*
  (timestampWithTimeZone & notNullable) `as` #updated_at
```

Then when you're defining you're schema you can `Join` the `MetaColumns` like

```Haskell
type Schema = '[
  -- ...
  "foo" ::: FooConstraints :=> Join FooColumns MetaColumns,
  -- ...
  ]
```

And in your `Definition` use `metaColumns` like

```Haskell
createTable #tableName
  (    
    -- ...
    :*  metaColumns
  ) (...)
```

**Comment by tuomohopia** [comment]
Thanks, even a more elegant solution that I was hoping for!

Works excellent, for others reading this just make sure you get the `metaColumns` type signature right:
```
metaColumns :: NP (Aliased (ColumnTypeExpression db)) MetaColumns
```
