### ISSUE TITLE
SQLite support?

### ISSUE THREAD

**Issue by amano-kenji** [morphismtech/squeal#338]
Is SQLite support planned? Or, is there something like squeal for SQLite?

It seems squeal is at the right level of abstraction, but I want to use SQLite.

I want to write SQL in haskell constructs.

**Comment by echatav** [comment]
This [question](https://github.com/morphismtech/squeal/issues/278) has a relevant discussion. One unique point about SQLite is that it is itself [dynamically typed](https://www.sqlite.org/datatype3.html#datatypes_in_sqlite) unlike PostgreSQL. This makes a Squeal adaptation of SQLite less straightforward and useful.

**Comment by amano-kenji** [comment]
Which libraries would you recommend for SQLite?

**Comment by amano-kenji** [comment]
How does sqlite-simple compare with higher abstraction libraries like squeal?

**Comment by echatav** [comment]
In use it's sort of similar to using Squeal or feels so to me, but with much less compile time checking, which sometimes necessitates more testing. A lot of the abstractions in Squeal are meant to allow you to compose together a `Query` (or a `Manipulation`), where in sqlite-simple, the `Query` type is most often constructed as a literal SQL string.

```Haskell
-- Squeal --
type DB = '["public" ::: '["tab" ::: '["col" ::: 'NotNull 'PGint4]]]

session :: PQ DB DB IO ()
session =
  manipulate_ $ insertInto_ #tab (Values (1 `as` #col) [2 `as` #col, 3 `as` #col])
  
-- sqlite-simple --
session :: Connection -> IO ()
session conn =
  execute_ conn "INSERT INTO tab(col) VALUES (1, 2, 3);"
```

**Comment by amano-kenji** [comment]
Okay. I am satisfied. Closing this.
