### ISSUE TITLE
None of the documentation can be accessed through hackage 

### ISSUE THREAD

**Issue by MangoIV** [morphismtech/squeal#341]
none of these are links: https://hackage.haskell.org/package/squeal-postgresql-0.9.1.0, I think something must have went wrong during publishing on hackage

**Comment by MangoIV** [comment]
https://hackage.haskell.org/package/squeal-postgresql-0.9.0.0 works as expected

**Comment by echatav** [comment]
Fixed, following https://github.com/kosmikus/records-sop/issues/12
