### ISSUE TITLE
Add support for JSON operators

### ISSUE THREAD

**Issue by ChShersh** [morphismtech/squeal#35]
PostgreSQL supports JSON functions and operators:

* https://www.postgresql.org/docs/9.5/static/functions-json.html

This is extremely convenient when your DB tables store JSON data. Would be good to have these functionality in `squeal` as well. Otherwise it requires more data types and functions to implement in order to parse JSON manually with `aeson` haskell library.

**Comment by echatav** [comment]
This would make a great and easy PR.

For instance:

```Haskell
(.->)
  :: json `In` '[ 'PGjson, 'PGjsonb]
  => Expression sch rels grp params (nullity json)
  -> Expression sch rels grp params (nullity 'PGint4)
  -> Expression sch rels grp params (nullity json)
(.->) = unsafeBinaryOp "->"
```

**Comment by echatav** [comment]
@ChShersh what was the schema/query you wanted translated?

**Comment by ChShersh** [comment]
@echatav I see that PR with JSON operators is merged. My particular issue is not only in JSON.
I think that this issue can be closed. Meanwhile I can try to describe query where I have problems under separate issue.
