### ISSUE TITLE
Are you guys affected by this ghc bug?

### ISSUE THREAD

**Issue by sdzx-1** [morphismtech/squeal#361]
Just out of curiosity, are you guys affected by this ghc bug?
You also make extensive use of type families.
https://gitlab.haskell.org/ghc/ghc/-/issues/8095

**Comment by echatav** [comment]
Maybe, it can definitely be slow when the schemas get large.

**Comment by sdzx-1** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/25360
If there are complex calculations, ghc will be stuck with about 20 fields.
