### ISSUE TITLE
Composability of queries ?

### ISSUE THREAD

**Issue by Raveline** [morphismtech/squeal#45]
I have a base query that joins four or five tables and retrieve ten fields. It's not a huge query, but it's complex enough that I want to keep it as maintainable as possible.

I'm likely to need several variation on this query, with different "where" clauses depending on how one would want to access the data.

I first thought this could be solved by making each part of the query composable. My first reflex was to isolate the select list; then the fromClause of the intermediary table.

However

- Isolating the select list from the rest of the query leads to multiple type errors (obviously, since the compiler cannot check that I'm selecting things that matches the virtual table to come).
- So I've tried creating a function that contains a select list plus the fromClause; this function will take a selectClause. This compiles. However, I find myself unable to sign the result (and using Intero to guess the signature leads to a giant wall of text).

I see two potential solutions:

- Using a view;
- Using a subquery.

I can live with both in my use case. However, I can't help but shake the feeling that composition of query should not be _that_ difficult. I am doing things wrong ? What do you suggest ?

**Comment by echatav** [comment]
What's your query? What other queries that are similar would you like to build from pieces. You might want to build a `FromClause` from which you can then build different `TableExpressions` and ultimately different `Query`s.

For example, suppose we have this schema.

```Haskell
:{
type family Schema :: SchemaType where
  Schema =
    '[ "orders" ::: 'Table (
         '["pk_orders" ::: 'PrimaryKey '["id"]
          ,"fk_customers" ::: 'ForeignKey '["customer_id"] "customers" '["id"]
          ,"fk_shippers" ::: 'ForeignKey '["shipper_id"] "shippers" '["id"]] :=>
         '[ "id"    ::: 'NoDef :=> 'NotNull 'PGint4
          , "price"   ::: 'NoDef :=> 'NotNull 'PGfloat4
          , "customer_id" ::: 'NoDef :=> 'NotNull 'PGint4
          , "shipper_id"  ::: 'NoDef :=> 'NotNull 'PGint4
          ])
     , "customers" ::: 'Table (
         '["pk_customers" ::: 'PrimaryKey '["id"]] :=>
         '[ "id" ::: 'NoDef :=> 'NotNull 'PGint4
          , "name" ::: 'NoDef :=> 'NotNull 'PGtext
          ])
     , "shippers" ::: 'Table (
         '["pk_shippers" ::: 'PrimaryKey '["id"]] :=>
         '[ "id" ::: 'NoDef :=> 'NotNull 'PGint4
          , "name" ::: 'NoDef :=> 'NotNull 'PGtext
          ])
     ]
:}
```

Then we can create a `FromClause` and ask GHCi to infer it's last type parameter using a wildcard

```Haskell
:{
let
  joined :: FromClause Schema '[] _
  joined = table (#orders `as` #o)
    & innerJoin (table (#customers `as` #c))
      (#o ! #customer_id .== #c ! #id)
    & innerJoin (table (#shippers `as` #s))
      (#o ! #shipper_id .== #s ! #id)
:}
error:
    • Found type wildcard ‘_’
        standing for ‘'['("o",
                          ("id" ::: 'NotNull 'PGint4)
                            : ColumnsToRelation
                                '["price" ::: ('NoDef :=> 'NotNull 'PGfloat4),
                                  "customer_id" ::: ('NoDef :=> 'NotNull 'PGint4),
                                  "shipper_id" ::: ('NoDef :=> 'NotNull 'PGint4)]),
                        '("c",
                          ("id" ::: 'NotNull 'PGint4)
                            : ColumnsToRelation '["name" ::: ('NoDef :=> 'NotNull 'PGtext)]),
                        "s"
                        ::: (("id" ::: 'NotNull 'PGint4)
                               : ColumnsToRelation '["name" ::: ('NoDef :=> 'NotNull 'PGtext)])]’
      To use the inferred type, enable PartialTypeSignatures
    • In the type signature: joined :: FromClause Schema '[] _
```

But that type's clearly too crazy to write down so we'll use another trick of GHCi. First clean up the type by getting it into a single line and then ask GHCi to evaluate it, that is apply all the time families by using the `:kind!` command.

```Haskell
:kind! '[ '("o", ("id" ::: 'NotNull 'PGint4) : ColumnsToRelation '["price" ::: ('NoDef :=> 'NotNull 'PGfloat4),"customer_id" ::: ('NoDef :=> 'NotNull 'PGint4),"shipper_id" ::: ('NoDef :=> 'NotNull 'PGint4)]),'("c",("id" ::: 'NotNull 'PGint4): ColumnsToRelation '["name" ::: ('NoDef :=> 'NotNull 'PGtext)]),"s"::: (("id" ::: 'NotNull 'PGint4): ColumnsToRelation '["name" ::: ('NoDef :=> 'NotNull 'PGtext)])]
'[ '("o", ("id" ::: 'NotNull 'PGint4) : ColumnsToRelation '["price" ::: ('NoDef :=> 'NotNull 'PGfloat4),"customer_id" ::: ('NoDef :=> 'NotNull 'PGint4),"shipper_id" ::: ('NoDef :=> 'NotNull 'PGint4)]),'("c",("id" ::: 'NotNull 'PGint4): ColumnsToRelation '["name" ::: ('NoDef :=> 'NotNull 'PGtext)]),"s"::: (("id" ::: 'NotNull 'PGint4): ColumnsToRelation '["name"::: ('NoDef :=> 'NotNull 'PGtext)])] :: [(ghc-prim-0.5.1.1:GHC.Types.Symbol,
                                          [(ghc-prim-0.5.1.1:GHC.Types.Symbol,
                                            NullityType)])]
= '['("o",
      '["id" ::: 'NotNull 'PGint4, "price" ::: 'NotNull 'PGfloat4,
        "customer_id" ::: 'NotNull 'PGint4,
        "shipper_id" ::: 'NotNull 'PGint4]),
    '("c", '["id" ::: 'NotNull 'PGint4, "name" ::: 'NotNull 'PGtext]),
    "s" ::: '["id" ::: 'NotNull 'PGint4, "name" ::: 'NotNull 'PGtext]]
```

It's starting to look nicer. Now, we can clean it up with some better spacing and replace type level pair with the `:::` operator and define the type

```Haskell
:{
type family Joined :: RelationsType where
  Joined =
    '[ "o" :::
       '[ "id" ::: 'NotNull 'PGint4
        , "price" ::: 'NotNull 'PGfloat4
        , "customer_id" ::: 'NotNull 'PGint4
        , "shipper_id" ::: 'NotNull 'PGint4
        ]
     , "c" :::
       '[ "id" ::: 'NotNull 'PGint4
        , "name" ::: 'NotNull 'PGtext
        ]
     , "s" :::
       '[ "id" ::: 'NotNull 'PGint4
        , "name" ::: 'NotNull 'PGtext
        ]
    ]
:}
```

Then we can fill in the wildcard

```Haskell
:{
let
  joined :: FromClause Schema ('[] :: [NullityType]) Joined
  joined = table (#orders `as` #o)
    & innerJoin (table (#customers `as` #c))
      (#o ! #customer_id .== #c ! #id)
    & innerJoin (table (#shippers `as` #s))
      (#o ! #shipper_id .== #s ! #id)
:}
```

I had to annotate the kind of the `'[]` because GHC whined. I might have been able to get away with using `-XPolyKinds`. Also, you don't even need to fill in the wildcard. You can use `-XPartialTypeSignatures` and leave it out as the error suggested.

Now we can use `joined` as a composable piece of queries like `select (#o ! #price) $ from joined & where_ (#o ! #price .> 5)`.

**Comment by Raveline** [comment]
First off, please let me thank you for this complete and enlightening example. I'm learning a lot thanks to you !

I managed to follow your process and I have something working.

Using the following RelationsType:

```
type family BoardSelection :: RelationsType where
  BoardSelection  =
    '[
     "b" :::
      '["board_id" ::: 'NotNull 'PGuuid,
        "title" ::: 'Null 'PGtext,
        "date" ::: 'NotNull 'PGdate]
    , "bi" :::
      '["board_id" ::: 'NotNull 'PGuuid
       , "item_id" ::: 'NotNull 'PGuuid
       , "order" ::: 'NotNull 'PGint2]
    , "it" :::
      '["item_id" ::: 'NotNull 'PGuuid
       , "quote_id" ::: 'Null 'PGuuid
       , "image_id" ::: 'Null 'PGuuid]
    , "q" :::
      '[ "quote_id" ::: 'Null 'PGuuid
       , "quote_title" ::: 'Null 'PGtext
       , "content" ::: 'Null 'PGtext
       , "quote_source" ::: 'Null 'PGtext]
    , "im" :::
      '["image_id" ::: 'Null 'PGuuid
       , "filepath" ::: 'Null 'PGtext
       , "image_source" ::: 'Null 'PGtext]
    ]
```

I was able to factor a FromClause:

```
boardTables :: FromClause Schema ('[] :: [NullityType]) BoardSelection
boardTables =
  table (#boards `As` #b)
    & innerJoin (table (#board_items `As` #bi)) (#b ! #board_id .== #bi ! #board_id)
    & innerJoin (table (#items `As` #it)) (#it ! #item_id .== #bi ! #item_id)
    & leftOuterJoin (table (#quotes `As` #q)) (fromNull false (#it ! #quote_id .== notNull (#q ! #quote_id)))
    & leftOuterJoin (table (#images `As` #im)) (fromNull false (#it ! #image_id .== notNull (#im ! #image_id)))
```

I'd still like to abstract away the NP part of the `select` I'll use it with, but I think I could find a way to do it using your method of reasoning with type-holes.

Since I'll apply various `where` clause to this relation types, I rendered it parametric - GHC still demands a type though.

```
boardTables :: FromClause Schema (params :: [NullityType]) BoardSelection
```

This allows me to write:

```
type BoardQuery params = Query Schema params BoardQueryResult
selectBoardByDay :: BoardQuery '[ 'NotNull 'PGdate ]
selectBoardByDay = select
  (  #b ! #board_id `As` #boardId
     :* #b ! #title
     :* #b ! #date
     :* #it ! #item_id `As` #itemId
     :* #q ! #quote_id `As` #quoteId
     :* #q ! #quote_title `As` #quoteTitle
     :* #q ! #content
     :* #q ! #quote_source `As` #quoteSource
     :* #im ! #image_id `As` #imageId
     :* #im ! #filepath
     :* #im ! #image_source `As` #imageSource
     :* Nil)
  (from boardTables
    & where_ (#b ! #date .== param @1))
```

(You can see why I want to abstract away the select list, it's way too long to repeat it over several queries !).

I think adding an example of composing queries in the documentation for query would be very nice - users are very likely to need it, and unless they're very familiar with type families, they might have a hard time figuring it out.

Once again, thank you for your quick, complete and extraordinarily helpful answer.

**Comment by Raveline** [comment]
I thought the subquery would be fine too (particularly for a relatively simple case like this).

But since I wanted to improve my understanding of Squeal and the ways it can be used (I'm trying to convince people at work to use it !), I still managed to isolate the field selection bit:

```
boardFields :: NP (Aliased (Expression Schema BoardSelection 'Ungrouped param)) BoardQueryResult
boardFields =
     #b ! #board_id `As` #boardId
     :* #b ! #title
     :* #b ! #date
     :* #it ! #item_id `As` #itemId
     :* #q ! #quote_id `As` #quoteId
     :* #q ! #quote_title `As` #quoteTitle
     :* #q ! #content
     :* #q ! #quote_source `As` #quoteSource
     :* #im ! #image_id `As` #imageId
     :* #im ! #filepath
     :* #im ! #image_source `As` #imageSource
     :* Nil
```

Of course, I've just realized the other queries I had in mind demanded grouping, so this makes it a bit useless :roll_eyes: since types won't align, but nonetheless, composability of queries is entirely doable.

**Comment by Raveline** [comment]
This issue can be closed, unless you want to keep it as a reminder for documenting the method you suggested to deduce intermediary types.

**Comment by mikeplus64** [comment]
@Raveline I use the following for this purpose:

For ungrouped stuff:

```haskell
-- wrapper for sensible order of type variables for use with TypeApplications
retCols :: forall ret rs ps s grp. SingRetCols s rs grp ps ret
        => NP (Aliased (Expression s rs grp ps)) ret
retCols = retCols_

class SingRetCols s rs grp ps ret where
  -- | Derive columns for a 'Returning' clause
  retCols_ :: NP (Aliased (Expression s rs grp ps)) ret

instance ( KnownSymbol name
         , rs ~ '[table ::: cols]
         , Has name cols nullty
         , SingRetCols s rs grp ps xs
         , IsLabel name (Aliased (Expression s rs grp ps) (name ::: nullty))
         , IsLabel name (Expression s rs grp ps nullty)
         ) =>
         SingRetCols s rs grp ps ((name ::: nullty) : xs) where
  {-# INLINE retCols_ #-}
  retCols_ =
    fromLabel @name `As` fromLabel @name :*
    retCols_

instance SingRetCols s rs ps grp '[] where
  {-# INLINE retCols_ #-}
  retCols_ = Nil
```

For grouped stuff:
```haskell
retCols2
  :: forall ret r rs ps s grp. SingRetCols2 s r rs grp ps ret
  => Alias r
  -> NP (Aliased (Expression s rs grp ps)) ret
retCols2 = retCols2_

class SingRetCols2 s r rs grp ps ret where
  -- | Derive columns for a 'Returning' clause
  retCols2_ :: Alias r -> NP (Aliased (Expression s rs grp ps)) ret

instance ( KnownSymbol name
         , Has r rs cols
         , Has name cols nullty
         , SingRetCols2 s r rs grp ps xs
         , IsQualified r name (Expression s rs grp ps nullty)
         ) =>
         SingRetCols2 s r rs grp ps ((name ::: nullty) : xs) where
  {-# INLINE retCols2_ #-}
  retCols2_ r =
    (r ! fromLabel @name) `As` fromLabel @name :*
    retCols2_ r

instance SingRetCols2 s r rs ps grp '[] where
  {-# INLINE retCols2_ #-}
  retCols2_ _ = Nil
```

Actual usage looks like: ```select (retCols @(TableToRelation OrdersTable))```

**Comment by mikeplus64** [comment]
In a way it's all rather mad to use Squeal to give us the requirement of e.g. writing type-safe select expressions, and then having a hairy typeclass or two to generate it, but I do really like that this gives us pretty maximal type-safety and confidence in the generated SQL.

**Comment by asheshambasta** [comment]
This may be slightly related, but in my case, I'm doing joins across tables where I'd like to represent the row-type of a table as a type in Haskell. 

For example, say I have an `image` table;
```haskell

type ImageSchema =
  '[ "imgType" ::: 'Typedef (PG (Enumerated ImgType))
   , "image" ::: 'Table (
       '[ "pkImage"     ::: 'PrimaryKey '["loc"] ] :=>
       '[ "loc"         ::: 'NoDef :=> 'NotNull 'PGtext
        , "imgtype"        ::: 'NoDef :=> 'NotNull (PG (Enumerated ImgType))
        , "height"      ::: 'NoDef :=> 'NotNull 'PGint2
        , "width"       ::: 'NoDef :=> 'NotNull 'PGint2
        , "blurry"      ::: 'NoDef :=> 'NotNull 'PGtext
        , "domain"      ::: 'NoDef :=> 'NotNull 'PGtext
        , "seq"         ::: 'NoDef :=> 'Null 'PGint2
        , "business_id" ::: 'NoDef :=> 'Null 'PGint4
        ]
       )
   ]
```
I'm referencing this table from another: 
```haskell
type BusinessSchema = ImageSchema ++
  '[ "businessType" ::: 'Typedef (PG (Enumerated BusinessType))
   , "business"     ::: 'Table (
       '[ "pkBusiness"  ::: 'PrimaryKey '["id"]
        , "fkBusinessLogo" ::: 'ForeignKey '["logo"] "image" '["loc"]
        , "fkBusinessCover" ::: 'ForeignKey '["cover"] "image" '["loc"]
        ] :=>
       '[ "id"          ::: 'NoDef :=> 'NotNull 'PGint8
        , "name"        ::: 'NoDef :=> 'NotNull 'PGtext
        , "slug"        ::: 'NoDef :=> 'NotNull 'PGtext
        , "busType"     ::: 'NoDef :=> 'NotNull (PG (Enumerated BusinessType))
        , "distId"      ::: 'NoDef :=> 'NotNull 'PGtext
        , "established" ::: 'NoDef :=> 'Null 'PGtime
        , "logo"        ::: 'NoDef :=> 'Null 'PGtext
        , "cover"        ::: 'NoDef :=> 'Null 'PGtext
        ])
     -- This is the join table joining the business table with itself.
   , "companyLocation" ::: 'Table (
       '[ "pkCompanyLocation" ::: 'PrimaryKey '["companyId", "locationId"]
        , "fkCompanyId"       ::: 'ForeignKey '["companyId"] "business" '["id"]
        , "fkLocationId"      ::: 'ForeignKey '["locationId"] "business" '["id"]
        ] :=>
       '[ "companyId"  ::: 'NoDef :=> 'NotNull 'PGint8
        , "locationId" ::: 'NoDef :=> 'NotNull 'PGint8
        ])
   ]
````

When doing Selects, I'd like to join across the `business` and `image` tables. However, I'd like the `image` columns to be neatly tucked into some underlying `image` type, and have it reflect in a `business` type with `logo :: Maybe Image` etc.

Is that possible?

Also, please pardon me if this is not related.

**Comment by echatav** [comment]
Hmmm, so I have thought about this issue before. When you do an left outer join for instance, you can imagine the result being the row on the left with a possibly empty set of rows on the right. Since there's no unique way to do this I left it for the user to handle after running the query.

**Comment by echatav** [comment]
With the current version of Squeal 0.4, you cannot _combine_ selection lists with full tables like you want, you can only do one or the other, so you must tediously specify the columns by hand. The next version Squeal 0.5 should enable a more succinctness by refactoring `select`s with a `Selection` type.

```Haskell
data Selection db params grp from row where
  List
    :: SListI row
    => NP (Aliased (Expression db params grp from)) row
    -> Selection db params grp from row
  Star
    :: HasUnique tab from row
    => Selection db params 'Ungrouped from row
  DotStar
    :: Has tab from row
    => Alias tab
    -> Selection db params 'Ungrouped from row
  Also
    :: Selection db params grp from right
    -> Selection db params grp from left
    -> Selection db params grp from (Join left right)
```

You will be able to combine a `List` and a `DotStar` with `Also`. Take a look at #84.

**Comment by tuomohopia** [comment]
I'm trying to compose queries by injecting Haskell values to a query.

My specific use case is composing a query conditionally, basically I'm trying to do something like this
```haskell
userUpdate :: Maybe Text -> Manipulation_ Schemas (UserId, UTCTime) ()
userUpdate mName = update_ #users updates (#id .== (param @1 & cast int8))
    where
        base = (Set (param @2) `as` #updated_at)
        updates = case mName of
                    Just name -> base :* (Set name `as` #name)
                    Nothing -> base
```

I guess injecting params like this isn't possible?
I gather `name` should be inferred as `name :: Expr ( 'NotNull 'PGtext)` but don't know how to get there. 

`HasParameter` doesn't seem to facilitate situations like this.

**Comment by echatav** [comment]
You can inject Haskell values into a Squeal expression using `literal` in `squeal-postgresql-0.5.2` which is renamed to `inline` for the next version.

**Comment by tuomohopia** [comment]
thank you! I don't know why I couldn't find that earlier. Still struggling joining the column updates though
