### ISSUE TITLE
Clarify behaviour on OnConflictDoRaise

### ISSUE THREAD

**Issue by Raveline** [morphismtech/squeal#46]
The current way conflicts are handled through onConflictDoRaise seems not very intuitive.

I had this block of instructions inside a MonadPQ:

```
void $ manipulateParams insertBoard (boardId, boardTitle, date)
uuids <- traverse newItem items
void $ manipulateParams deleteBoardItems (Only boardId)
associateBoardAndItems boardId uuids
```

Insert board is defined as having `OnConflictDoRaise (Returning Nil)`. However, if the function is only defined with the lines above, the following instructions will be executed (and the raised error seem to be silent, which is rather surprising).

To make sure that this block was not failing I had to put it in a transaction:

```
transactionally_ $ do
      void $ manipulateParams insertBoard (boardId, boardTitle, date)
      uuids <- traverse newItem items
      _ <- manipulateParams deleteBoardItems (Only boardId)
      associateBoardAndItems boardId uuids
```

Which is obviously cleaner - and probably the way to do this kind of things.

However, I believe this still leaves two issues:

1°) The error received is not very explicit. How can I guess which of the Unique clauses in a table, for instance, would be broken from this:
```
       uncaught exception: ErrorCall
       traversePrepared: LibPQ.prepare status FatalError
```
2°) It seems to me that errors, even outside of a transaction, should not be silent if one uses `OnConflictDoRaise`, this is not the behaviour you would reasonably expect.

**Comment by echatav** [comment]
This should be better documented and integrated in Squeal's error reporting as you point out, but you should be able to combine `Squeal.PostgreSQL.liftResult` with `Database.PostgreSQL.LibPQ.resultErrorMessage` to get verbose error results. We should test against your exact situation in #36 and get better error handling generally.

**Comment by Raveline** [comment]
If you're okay with it, I should be able to push a PR setting up a small test using hspec with an example case with a violation of a constraint outside of a transaction.
