### ISSUE TITLE
defaultMain in Migration

### ISSUE THREAD

**Issue by echatav** [morphismtech/squeal#57]
It would be nice to have a function

```Haskell
defaultMain
  :: ByteString -- ^ connection string
  -> AlignedList (Migration IO) schema0 schema1 -- ^ migrations
  -> IO ()
```

which generates a CLI program to manage migrations.

**Comment by Raveline** [comment]
I've put the result of our session in this branch:
https://github.com/Raveline/squeal/tree/migration-main

**Comment by echatav** [comment]
* We need some configurability in the migration table (name, schema, etc).
* It's bad that `migrateUp` et al. have complicated kinds with MigrationTable

Instead it should look like:

```Haskell
migrateUp
  :: MonadBaseControl IO io
  => QualifiedAlias sch tab -- ^ migration table alias
  -> AlignedList (Migration io) schemas0 schemas1 -- ^ migrations to run
  -> PQ schema0 schema1 io ()
```

Question: Does it make sense or not to host the migration table alias in `Migration` like

```Haskell
data Migration
  (sch :: Symbol) (tab :: Symbol)
  (io :: Type -> Type)
  (schemas0 :: SchemasType) (schemas1 :: SchemasType)
```

**Comment by Raveline** [comment]
Hello, @echatav ! I'm still working on this, I left you a long implementation question on Skype if you have a few minutes one of these days.

**Comment by echatav** [comment]
Sorry I missed this. I think for now let's see a solution that runs all the migrations fed, leave out `SingleUp` and `SingleDown`. They don't even make sense if your list is `Done`.

The other thing is we want to make running migrations more compatible with other `PQ` operations so that the signature of `migrateUp` is something more like

```Haskell
migrateUp
  :: MonadBaseControl IO io
  => AlignedList (Migration io) schemas0 schemas1
  -> PQ schemas0 schema1 io ()
```

Although this leaves a weird question as to what table to store the migration info in and whether that table should or shouldn't be tracked in the schemas.
