### ISSUE TITLE
Add range types

### ISSUE THREAD

**Issue by echatav** [morphismtech/squeal#59]
Add range types. [documentation](https://www.postgresql.org/docs/9.3/static/rangetypes.html)

**Comment by echatav** [comment]
Among the interval libraries, it looks like `data-interval`'s [`Interval`](http://hackage.haskell.org/package/data-interval-1.3.0/docs/Data-Interval.html#t:Interval) type looks like it most closely matches postgres's `range` types.

**Comment by AnthonySuper** [comment]
I've started work on this on my fork, but I've ran into the interesting problem that the `@>` and some similar operators work both on ranges and on json types. Currently, they're defined for JSON in Squeal. What do you reckon is the best way to work around this?

**Comment by echatav** [comment]
Sweet!

> `@>` and some similar operators work both on ranges and on json types.

Looks like array types too. Probably a job for a multi parameter type class like

```Haskell
class PGcontains container contained where
  (.@>)
    ::  Expression schema from grouping params (nullity container) -- ^ container
    -> Expression schema from grouping params (nullity contained) -- ^ contained
    -> Condition schema from grouping params
  (.@>) = unsafeBinaryOp "@>"
```

You might want to do just one new constructor for `PGType` like `PGrange PGType` (unless it needs a `NullityType`), rather than a constructor for each possible type. Then you can have `TypeExpressions` for the built-in range types and a `createTypeRange` function for new user defined range types.

**Comment by AnthonySuper** [comment]
I implemented the typeclass as you suggested in [my add-ranges branch](https://github.com/AnthonySuper/squeal/tree/add-ranges). I'm sadly a bit unsure what else I need to do to get range types working (if there's actually anything else to do). Mind having a look?

**Comment by echatav** [comment]
Great! I took a look. One thing I would do is to consolidate all the `'PGXrange` types into a single `PGrange PGType` branch. This would let you eliminate the `PGRangeSubtype` type family and reduce some boilerplate. Next you need to create type expressions for the built-in range types, e.g.

```Haskell
int4range :: TypeExpression schema ('PGrange 'PGint4)
int4range = UnsafeTypeExpression "int4range"
```

Next you need to create a CREATE statement for non-built-in range types, e.g.

```Haskell
createTypeRange
  :: KnownSymbol range
  => Alias range
  -> TypeExpression schema ty
  -> Definition schema (Create range ('Typedef ('PGrange ty)) schema)
createTypeRange alias ty = UnsafeDefinition $
  "CREATE" <+> "TYPE" <+> renderAlias range <+> "AS" <+> "RANGE" <+>
  parenthesized ("subtype" <+> "=" <+> renderTypeExpression ty)
```

You can consider adding options to the CREATE such as `subtype_diff` but a simple version without is fine.

Next, you need to add expressions for constructing ranges, e.g.

```Haskell
range
  :: Interval (Expression schema from grouping params ty)
  -> Expression schema from grouping params ('PGrange ty)
```

Next, you need to add support for [operators](https://www.postgresql.org/docs/current/functions-range.html#RANGE-OPERATORS-TABLE) and [functions](https://www.postgresql.org/docs/current/functions-range.html#RANGE-FUNCTIONS-TABLE) on range expressions. Some of this may benefit from a little creativity. For instance, some of the operators look numeric like unions, intersections and differences so maybe a `Num` instance would be appropriate?

Next, you need to add binary instances.

```Haskell
instance ToParam x pg => ToParam (Interval x) ('PGrange pg) where toParam = _
instance FromValue pg y => FromValue ('PGrange pg) (Interval y) where fromValue =_
```

And test that they work, maybe add a doctest. You will probably have to do some digging to find out how Postgres represents range types in binary format.

**Comment by echatav** [comment]
@AnthonySuper Checking in, have you worked on this more?

**Comment by AnthonySuper** [comment]
I haven't in a while, unfortunately. I'm going to try to work on this tomorrow.

**Comment by echatav** [comment]
done in #209
