### ISSUE TITLE
Add monetary types

### ISSUE THREAD

**Issue by echatav** [morphismtech/squeal#60]
The `PGmoney` Postgres type should correspond to the `Centi Int64` Haskell type. Here's [Centi](https://www.stackage.org/haddock/lts-12.10/base-4.11.1.0/Data-Fixed.html#t:Centi) from `Data.Fixed`. Here's [documentation](https://www.postgresql.org/docs/9.1/static/datatype-money.html) for Postgres' money type.

**Comment by sonatsuer** [comment]
What do you mean by `Centi Int64` here? It seems that `Centi` has kind `*`.

**Comment by echatav** [comment]
You're right! I didn't notice that you can't set the size of the underlying integer representation of `Fixed`; it's stuck with variable precision `Integer` when I think we'd want fixed precision `Int64`. Assuming there's no existing type in base or some library that `Squeal` already depends on that's appropriate, I guess just define `newtype Money = Money { cents :: Int64 }` and give it all the numeric hierarchy instances `Num`, `Frac`, etc. that are appropriate. You might need to look into `locale`s and what impact they have on Postgres' `money` type to see if this makes sense.

**Comment by echatav** [comment]
Cool. Kind of a bigger issue than I guessed :-)

**Comment by echatav** [comment]
On the other hand, is `money` in postgres an ISO-4217 compliant thingamabob? I think it's much simpler than that:

> Name | Storage Size | Description | Range
> money | 8 bytes | currency amount | -92233720368547758.08 to +92233720368547758.07

Compare that to `int8`

> Name | Storage Size | Description | Range
> bigint | 8 bytes | large-range integer | -9223372036854775808 to 9223372036854775807

Beyond concerns about the `lc_monetary` setting, there's less to it than it appears. You're right about the instances on the Haskell side though. `Money` shouldn't be a `Num`, it's a 1-dimensional vector space maybe, although even there you run into the question of rounding...

I think a basic implementation is Squeal would add a `PGmoney` type

```Haskell
data PGType
  = ..
  | PGmoney
  | ..
```

add a Haskell `Money` type

```Haskell
newtype Money = Money { cents :: Int64 }
```

with a `PG` instance

```Haskell
type instance PG Money = 'PGmoney
```

and binary instances

```Haskell
instance ToParam Money 'PGmoney where ..
instance FromValue 'PGmoney Money where ..
```

and that should be good enough!

**Comment by sonatsuer** [comment]
OK. I will start implementing. We can discuss more on an actual pull request later if we need to.

**Comment by echatav** [comment]
...and a type expression

```Haskell
money :: TypeExpression schema (nullity 'PGmoney)
```

**Comment by echatav** [comment]
hello @sonatsuer just checking in to see if you've made any progress on this issue?

**Comment by sonatsuer** [comment]
hello @echatav. sorry for the delay. i started working on it but had to halt due to personal stuff. will get back to it as soon as i can.

**Comment by echatav** [comment]
@sonatsuer Checking in, have you worked on this more?
