### ISSUE TITLE
SELECT DISTINCT ON(...) ...

### ISSUE THREAD

**Issue by mikeplus64** [morphismtech/squeal#62]
This would be very useful. I have no idea how to type the list of columns to use for the `ON` clause.

**Comment by echatav** [comment]
It could be

```Haskell
selectDistinctOn
  :: ( SListI distincts
      , SListI columns
      , 1 <= Length distincts
      , 1 <= Length columns )
  => NP (Aliased (Expression schema from 'Ungrouped params)) distincts
  -- ^ distinct on
  -> NP (Aliased (Expression schema from 'Ungrouped params)) columns
  -- ^ select list
  -> TableExpression schema params from 'Ungrouped
  -- ^ intermediate virtual table
  -> Query schema params columns
```

This wouldn't statically require as the documentation notes:

> The DISTINCT ON expression(s) must match the leftmost ORDER BY expression(s).

There's no way Squeal could do this since the `orderBy` expressions are not statically tracked. I think that's ok though. Just document the requirement. It's _possible_ to statically track that info in the `TableExpression` type but not worth it I think unless there are more reasons.

**Comment by echatav** [comment]
Another idea. The “distinct on” expressions can be made to match the leftmost “order by” expressions simply by pretending them to the “orderByClause” of the TableExpression.

**Comment by echatav** [comment]
```Haskell
selectDistinctOn
  :: (SListI columns, columns ~ (col ': cols))
  => [SortExpression outer commons 'Ungrouped schemas params from]
  -> Selection outer commons 'Ungrouped schemas params from columns
  -- ^ selection
  -> TableExpression outer commons 'Ungrouped schemas params from
  -- ^ intermediate virtual table
  -> Query outer commons schemas params columns
selectDistinct selection tab distincts = UnsafeQuery $
  "SELECT DISTINCT ON"
  <+> parenthesized (commaSeparated (renderDistinctOn <$> distincts))
  <+> renderSQL selection
  <+> renderSQL (tab {orderByClause = distincts <> orderByClause tab )
  where
    renderDistinctOn (_ expr) = renderSQL expr
```
