### ISSUE TITLE
Support arithmetic operations on PGtimestamp / PGinterval

### ISSUE THREAD

**Issue by bqv** [morphismtech/squeal#65]
Not sure how to implement this one...

**Comment by bqv** [comment]
It completely went over my head that arithmetic operations aren't even properly instanced. Perhaps a `.-`, `.+`, `.*`, `./` set to complement the comparison operators?

**Comment by bqv** [comment]
Nevermind, that was an unrelated error.

**Comment by bqv** [comment]
I lied, I can find no instances for Num on PGtimestamp or PGinterval. Sorry for the spam

**Comment by echatav** [comment]
[Documentation](https://www.postgresql.org/docs/10/static/functions-datetime.html)

Looks like a `Num` instance won't work so maybe some custom operators?
