### ISSUE TITLE
Passing a list of values as parameter

### ISSUE THREAD

**Issue by Raveline** [morphismtech/squeal#74]
I'm trying to do a classical:

```SQL
SELECT bar FROM fuzz
WHERE foo IN ('some', 'list', 'of', 'parameters', 'of', 'various', 'length');
```

The base query is easy enough:

```haskell
myQuery :: Query MySchema '[] FooBarFuzzResults
myQuery = select (#fuzz ! #bar) (from #fuzz)
```

If I understand properly the way one would go around building this type of query, there is way to use the `params` to build up the "WHERE IN" clause. But I should be able to emulate it through a subquery:

```haskell
type FooResults = '[ "foo" :: 'NotNull 'PGtext ]

myQuery :: Query MySchema '[] FooResults -> Query MySchema '[] FooBarFuzzResults
myQuery vals = select (#fuzz ! #bar) (from #fuzz & where_ (#fuzz ! #foo `in_` vals))
```

And I should be able to build my "vals" parameter using `values`.

This calls for two questions:

- Is this the intended way of doing it ?
- Are there plans to implement a simplified syntax ? I am a bit sad of not being able to pass my list of arguments through the usual `param`.

If the answer to the first question is "yes", I'll probably push an example in the Query module because this is a common use-case and it would probably be good to have a quick reference on how to write these types of queries.

**Comment by echatav** [comment]
> Is this the intended way of doing it ?
Yes
> Are there plans to implement a simplified syntax ?
No.

You might do something like:
```Haskell
valuesAs
  :: Alias col
  => Expression schema '[] 'Ungrouped params ty
  -> [Expression schema '[] 'Ungrouped params ty]
  -> Query schema params '[col ::: ty]
valuesAs col x xs = values (x `As` col) (map (`As` col) xs)
```

> I am a bit sad of not being able to pass my list of arguments through the usual `param`.

You can't pass variadic parameters. If you want to pass the values as a parameter you'd have to use an array.

**Comment by Raveline** [comment]
It absolutely makes sense. I thought about PG Array as a solution, but it is really not satisfying either, so I think the `in` with the subquery is better.

I suggest:

- Adding your `valuesAs` in the code - it's a fairly common use-case.
- Adding this example in the documentation of the Query module to show what is the intended way of using a list of parameters.
- Underlining the fact that variadic parameters are not supported.

As always, I'm ready to PR this.

**Comment by echatav** [comment]
Ok :-) Would you like to pair code on something?

**Comment by Raveline** [comment]
Oh ! With pleasure, though we'll need to find a suitable time for our different timezones !

**Comment by echatav** [comment]
Indeed, and it's sleepy time for me now!

**Comment by Raveline** [comment]
Good night then :) I'll send you my Skype nickname through Twitter.

**Comment by echatav** [comment]
alternative: Make an `Aliasable` instance for lists of expressions

```Haskell
instance Aliasable col
  [Expression schema from grp params ty]
  [Aliased (Expression schema from gap params) (col ::: ty)]
```

Then you can re-use `values` with just a little more aliasing work

```Haskell
myQuery :: Query MySchema '[] FooBarFuzzResults
myQuery =
  select (#fuzz ! #bar) (from #fuzz
    & where_ (#fuzz ! #foo `in_`
        values ("some" `as` #foo) (["list", "of", "parameters", "of", "various", "length"] `as` #foo)))
```

Still a bit ugly.

**Comment by adfretlink** [comment]
I have tried both solution. I think `valuesAs` is still the better option, though I would probably fuse the two first parameter and use NonEmpty.

However I'm still having trouble finding a good solution to have a morphing from `[a]` to the proper `Expression` type.

**Comment by adfretlink** [comment]
What do you think about something like this:

```
promote :: (a -> ByteString) -> a -> Expression schema '[] 'Ungrouped params ty
promote render = UnsafeExpression . render

valuesAs
  :: (KnownSymbol col)
   => Alias col
  -> NonEmpty a
  -> (a -> ByteString)
  -> Query schema params '[col ::: ty]
valuesAs' col vals renderer =
  let (x:|xs) = promote renderer <$> vals
  in values (x `as` col) (fmap (`as` col) xs)
```

It it still fairly verbose though. `postgresql-simple` uses a special constructor `In` for this type of parameters, and I have to admit that it feels much more user-friendly.

**Comment by echatav** [comment]
Since this is such a common case, let's add a function

```
inList
  :: Expression schema from grp params ty
  -> [NP (Expression schema from grp params) ty]
  -> Aliased (Expression schema from grp params) (col ::: ty)
  -> Condition schema from grp params
inList expr exprs element = element `in_` (values (expr `as` col) (map (`as` col) exprs)
  where
    col = Alias @col
```

```
myQuery :: Query MySchema '[] FooBarFuzzResults
myQuery =
  select (#fuzz ! #bar) (from #fuzz
    & where_ (#foo & inList "some" ["list", "of", "parameters", "of", "various", "length"])
```

I'd rather avoid using the `NonEmpty` datatype because it has an unsafe [fromList](https://hackage.haskell.org/package/semigroups-0.16.0.1/docs/src/Data-List-NonEmpty.html#fromList) function.

**Comment by echatav** [comment]
Or maybe that should be the default `in_` function? Maybe do the same for all the subquery expressions? Two forms `rowOp` and `op` with

```Haskell
-- | generalized subquery expression
rowOp
  ::  SListI row
  => NP (Aliased (Expression schema from grp params)) row
  -> Query schema params row
  -> Condition schema from grp params

-- | values subquery expression
op
  :: Expression schema from grp params ty
  -> [NP (Expression schema from grp params) ty]
  -> Aliased (Expression schema from grp params) (col ::: ty)
  -> Condition schema from grp params
op expr exprs val = (val :* Nil) `rowOp` qry
  where
    col = Alias @col
    qry = values (expr `as` col) (map (`as` col) exprs)
```

**Comment by Raveline** [comment]
I think your `inList` is a good solution, though I quite like your `op` and `rowOp`.

`NonEmpty` has indeed the unsafe `fromList` function (though I use the safer `nonEmpty` function myself), but writing it like you do forces client code to deconstruct lists in the parameters when they want to build these expressions. But that's an acceptable cost I suppose.

That still leave us with the difficulty of promoting a list of naive values - say a list of Text - to a list of `Expression`. What would you suggest for this ?

**Comment by Raveline** [comment]
Ah. I just realized `eqAny` and `eqAll` take queries, so I see you've thought of that :p My mistake then.

**Comment by echatav** [comment]
Along this thread of refactoring subquery expressions. One thing that's currently annoying is that Squeal has a new function for each operator. Would something like this work instead?

```Haskell
data Qualification = Some | Any | All

-- | >>> printSQL $ op true (.==) All values_ (true `as` #foo)
-- TRUE = ALL (SELECT * FROM (VALUES (TRUE)) AS t ("foo"))
op
  :: Expression schema from grp params ty -- ^ expression
  -> (Expression schema from grp param ty -> Expression schema from grp param ty -> Expression schema from grp param ty) -- ^ operator
  -> Qualification
  -> Query schema params '[alias ::: ty] -- ^ subquery
  -> Expression schema from grp params (nullity 'PGbool)
```
