### ISSUE TITLE
Documentation on enumerated types

### ISSUE THREAD

**Issue by asheshambasta** [morphismtech/squeal#80]
So I'm quite new to type-level programming in Haskell and my question might be totally misplaced. However, in that case, please feel free to close this issue with a minor pointer to where I should be looking. 

I've been paying around with Squeal and I'm intrigued. I wanted to define an `ENUM` type from an ADT; namely [this](https://gist.github.com/asheshambasta/31c7fe8077961ac47489af3dc9b4f487#file-squeal-hs-L80).

However, I cannot really figure out how to use this in my `setup` definition, which seems to point that I should have some sort of `ColumnTypeExpression` that represents my ENUM column. 

Any pointers on how to achieve that would be nice.

**Comment by echatav** [comment]
Specifically, your `Schema` should contain

```Haskell
"auth_status" ::: 'Typedef (PG (Enumerated AuthStatus))
```

and your `setup` should contain

```Haskell
createTypeEnumFrom @AuthStatus #auth_status
```

then you can reference that type (where you have `undefined`) using

```Haskell
typedef #auth_status
```

**Comment by asheshambasta** [comment]
Hello @echatav @Raveline, thank you very much for taking the time to clarify this. Also, thanks for a library that I, as a type-level beginner, find quite mind-bending. I'm just not familiar with type-level programming and syntax in Haskell to grok this completely. 

Also, coming back to what @echatav suggested, do you mean something on the lines of this in my Schema? 

```haskell
-- | Define the type that corresponds to all the schemata in the database.
type Schema =
  '[ "authStatus" ::: 'Typedef (PG (Enumerated AuthStatus))
   , "auth" ::: 'Table (
       '[ "pkAuth" ::: 'PrimaryKey '["user"] ] :=>
       '[ "user" ::: 'NoDef :=> 'NotNull 'PGtext
        , "jwk" ::: 'NoDef :=> 'NotNull 'PGtext
        ])
   , "areaNode" ::: 'Table (
       '[ "pkAreaNode" ::: 'PrimaryKey '["id"] ] :=>
       '[ "id" ::: 'NoDef :=> 'NotNull 'PGtext
        , "name" ::: 'NoDef :=> 'Null 'PGtext
        , "desc" ::: 'NoDef :=> 'Null 'PGtext
        , "pairingStatus" ::: 'NoDef :=> 'NotNull 'PGtext -- todo: custom types
        , "updated" ::: 'NoDef :=> 'Null 'PGtimetz
        , "created" ::: 'NoDef :=> 'NotNull 'PGtimetz
        ])
   , "authData" ::: 'Table (
       '[ "pkAuthData" ::: 'PrimaryKey '["userId", "areaNodeId"]
        , "fkAuthUserId" ::: 'ForeignKey '["userId"] "auth" '["user"]
        , "fkAuthAreaNodeId" ::: 'ForeignKey '["areaNodeId"] "areaNode" '["id"]
        ] :=>
       '[ "userId" ::: 'NoDef :=> 'NotNull 'PGtext
        , "areaNodeId" ::: 'NoDef :=> 'NotNull 'PGtext
        , "status" ::: 'NoDef :=> 'NotNull undefined -- ??? 
        , "updated" ::: 'NoDef :=> 'NotNull 'PGtimetz
        ])
   ]
```

I'm still a bit lost on how to _reference_ a defined type as a type of a column in a Table definition.

**Comment by echatav** [comment]
You got it.

**Comment by asheshambasta** [comment]
@echatav Great! Thanks so much for taking the time to clarify this. It feels great to have learned something new and Squeal helped me achieve that. Thank you so much for the effort with this library. I hope I can contribute back someday soon. 

Which brings me to another question: why the name, though? 

##
 
PS: please feel free to close this issue since its quite clear in my mind now.

**Comment by echatav** [comment]
The name comes from SQL. It means “a long, high-pitched cry or noise.” It’s also the noise a pig makes :-)

**Comment by asheshambasta** [comment]
@echatav Sorry to be bothering you with this, but how does one go about when trying to use the `enum` in a `where_` expression?

**Comment by asheshambasta** [comment]
@echatav 
So playing around with this has led me to another point of confusion. 

Say I have a simple enum-type:

```haskell
data Status = Ok | NotOk deriving (Generic, Show, Enum, Ord, Bounded)
```
Now, I'd like to use this in my schema as a type; for which, I use `createTypeEnumFrom` in my `Definition`. 

However, retrieving this value in a query leads to:
```
    • Could not deduce (FromValue
                          ('PGenum '["Ok", "NotOk"]) Status)
```

So I take a look at `FromValue` [here](http://hackage.haskell.org/package/squeal-postgresql-0.4.0.0/docs/Squeal-PostgreSQL-Binary.html#t:FromValue).

While I can define this by hand, can I derive this somehow automatically? 

Why I'm asking for this is: some enumerated types change, and it seems a bit fidgety and error prone to have handwritten parsers.

**Comment by echatav** [comment]
The easy solution is to use the newtyped `Enumerated Status`. This tells Squeal you want to store that field as an enum rather than say json for instance. If you really want to specify once and for all that `Status` will always be stored as an enum then define instances like:

```Haskell
type instance PG Status = 'PGenum '["Ok", "NotOk"]
instance ToParam Status ('PGenum '["Ok", "NotOk"]) where toParam = toParam . Enumerated
instance FromValue ('PGenum '["Ok", "NotOk"]) Status where fromValue = getEnumerated <$> fromValue
```

**Comment by echatav** [comment]
You can open new issues for questions, @asheshambasta

**Comment by echatav** [comment]
Take a look at the haddocks in `Squeal.PostgreSQL.Binary` [here](https://hackage.haskell.org/package/squeal-postgresql-0.4.0.0/docs/Squeal-PostgreSQL-Binary.html). In particular there's an example of an enumerated type `Schwarma` that shows a prototypical example.

**Comment by asheshambasta** [comment]
@echatav 
Thanks for your time and your patience with your replies. I didn't know where else to put this but I'd really like to thank you for this library. I'd love to contribute somewhere in the future soon, but my understanding is currently limited. I'm working to improve that, moreso since I'm using Squeal for one of the most critical pieces of our infrastructure.

**Comment by echatav** [comment]
I'm very happy to hear that! I'm so excited that folks find Squeal useful :-)
