### ISSUE TITLE
mysql port

### ISSUE THREAD

**Issue by kuribas** [morphismtech/squeal#81]
I wonder if there is any interest in a mysql port?  Would this reuse code, or be just a different project?  I see advantages for both approaches, if it's a different project, it's easier to make it specific to mysql (for example parameter passing, different quoting rules, ...)

**Comment by echatav** [comment]
I imagine it would be another library `squeal-mysql` which can reuse code from `squeal-postgresql`. Similar to how the `mysql-simple`, `postgresql-simple`, etc. ecosystem. I don't have the bandwidth to work on such a project but I'd be happy to support anyone who would like to try.
