### ISSUE TITLE
connectdb with correct schema

### ISSUE THREAD

**Issue by asheshambasta** [morphismtech/squeal#85]
I'm making a connection to a DB called `core` that contains a `CoreSchema`; that has the same name as that of my main DB  type

```haskell
type CoreSchema = Schema1 ++ Schema2 ++ ... 
```

My connection string is 

```
"host=localhost dbname=core user=calocal application_name=CoreService options='-c search_path=\"CoreSchema\"'"
```
(I've tried with and without the _options_ above)

Then I'm doing `connectdb @CoreSchema connStr`; which is as per the documentation [here](https://hackage.haskell.org/package/squeal-postgresql-0.4.0.0/docs/Squeal-PostgreSQL-PQ.html#v:connectdb).
However, running queries seem to fail with "relation not found", which seems like the incorrect schema is selected, or set in my `search_path`. 

I've set Postgresql logging to quite verbose and these are the logs: 

```
λ> :main -n "core" --log-level "Level 0" -D "host=localhost dbname=core user=calocal application_name=CoreService options='-c search_path=\"CoreSchema\"'" -R "redis://" --server-port 10000
[INFO] [27/Dec/2018:16:15:56 +0100] ["core/Startup"] Starting up
DEBUG:  CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 0/1/0
[INFO] [27/Dec/2018:16:15:56 +0100] ["core/Startup"] Redis/DB are connected.
[INFO] [27/Dec/2018:16:15:56 +0100] ["core"] Starting servers
DEBUG:  parse <unnamed>: SELECT "c"."id" AS "id", "c"."name" AS "name", "c"."slug" AS "slug", "pc"."id" AS "pId", "pc"."name" AS "pName", "pc"."slug" AS "pSlug" FROM "category" AS "c" INNER JOIN "category" AS "pc" ON ("c"."parentId" = "pc"."id") WHERE ("c"."id" = ($1 :: int2));
DEBUG:  StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0
DEBUG:  relation "category" does not exist
LINE 1: ...c"."name" AS "pName", "pc"."slug" AS "pSlug" FROM "category"...
                                                             ^
PQException {sqlExecStatus = FatalError, sqlStateCode = Just "42P01", sqlErrorMessage = Just "ERROR:  relation \"category\" does not exist\nLINE 1: ...c\".\"name\" AS \"pName\", \"pc\".\"slug\" AS \"pSlug\" FROM \"category\"...\n                                                             ^\n"}

```

I've tried running the same query from within another GUI based DB client (dbeaver) and the query checks out when the correct schema and db is set as "Active". 

What could be going on here?

## 

Edit: As it turns out; creating this tables within the `public` schema seems to _alleviate_ the problem.

**Comment by echatav** [comment]
Squeal <= 0.4 does not support multiple schemas, only “public” as you’ve found out. The next version will have multi-schema support.

**Comment by asheshambasta** [comment]
@echatav alright thanks for clarifying. Maybe this can be clarified in the docs I've mentioned above?
