### ISSUE TITLE
Compiler accepts lists as return type but they fail at execution

### ISSUE THREAD

**Issue by adfretlink** [morphismtech/squeal#87]
If you do not use `RowPG` (which is probably a bad idea, but bear with me), you can devise a return type like this one:

```
type ExampleResult =
  [
    "foo" ::: 'Null 'PGtext
  , "someList" ::: 'NotNull ('PGvararray ('NotNull 'PGtext))
  ]
```

Should you try to use `getRow` on this return type to produce a:

```
data ExampleResult =
   ExampleResult { foo :: Maybe Text, someList :: [Text] }
```

You will get a rather unhelping error at execution:

```
ParseException "getRows: End of input"
```

I'll admit I am not exactly sure I understand how type checking is done in this area. I suspect there is a strong dependency upon Generic-SOP here, which would prevent us from making it impossible to compile.

In any case, this should warrant a list a warning in the documentation, don't you think ?

**Comment by echatav** [comment]
Some more details would help. It should _not_ produce a runtime error. I didn't make instances for list types but for `Vector`. This could probably use some improvements.

**Comment by Raveline** [comment]
The only example I have now is proprietary code, I'll try to come up with a complete example (maybe a supplmentary test case if that helps).

**Comment by asheshambasta** [comment]
From what I see, I can reproduce this; although the error I'm seeing is a bit different:
```
ParseException "firstRow: End of input"
```
This seems to indeed be related to arrays. Basically, you need to accept the offending column as the same fieldname inside a type, of type `[a]` instead of `Vector a` and this error can be reproduced.

**Comment by echatav** [comment]
I believe this bug arises from the complicated way instances for arrays are built.

It might be convenient to introduce an `Array` newtype similar to `Json`, `Jsonb`, `Composite`, `Enumerated` to simply indicate when you want to store a field as an array in the database. Then we could make instances for `Array v` when `v` is a `Vector`, whether that's vanilla, `Unboxed` or `Storable` and potentially also for lists.

**Comment by adfretlink** [comment]
@asheshambasta : Same error, you probably used `getFirstRow` rather than `getRows`, no ?

@echatav : I agree and I think that an `Array` newtype is a wonderful idea.

**Comment by asheshambasta** [comment]
@adfretlink that is correct. 
@echatav +1 for the Array idea too. 
I think overall this is a minor gotcha, but otherwise it works perfectly with `Vector`.
