### ISSUE TITLE
Subquery with parameters / recursive queries 

### ISSUE THREAD

**Issue by ilyakooo0** [morphismtech/squeal#99]
From what I have gathered, subqueries get the same parameters as the query, inside which they are nested. 

If I am correct, I am lead to believe that recursive queries are not supported. (Also because it might not type check because the query itself is not "in its own scope".)

ref: https://www.postgresql.org/docs/9.1/queries-with.html

**Comment by echatav** [comment]
There is no support currently for `WITH RECURSIVE` statements. However, I'm adding support the kind of outer scope you mention for nested queries such as detailed in #86. Perhaps this change might help in adding support for recursive queries?

**Comment by echatav** [comment]
I think it might actually be easier to implement `WITH RECURSIVE` than I had thought. Here's a first attempt.

```Haskell
withRecursive
  :: Aliased (Query outer (recursive ': commons) schemas params) recursive
  -> Query outer (recursive ': commons) schemas params row
  -> Query outer commons schemas params row
withRecursive (recursive `As` alias) query = UnsafeQuery $
  "WITH RECURSIVE" <+> renderSQL alias
    <+> parenthesized ("")
    <+> "AS" <+> parenthesized (renderSQL recursive)
    <+> renderSQL query
```

And here's an example in use
```Haskell
>>> :{
  let
    one :: Expr ('NotNull 'PGint4)
    one = 1
    query :: Query_ schema () (Sum Int32)
    query = withRecursive
      ( values_ (one `as` #n)
        `unionAll`
        select_ ((#n + 1) `as` #n)
          (from (common #t) & where_ (#n .< 100)) `as` #t )
      ( select_ (sum_ (All #n) `as` #getSum) (from (common #t) & groupBy Nil))
  in printSQL query
:}
WITH RECURSIVE "t" () AS ((SELECT * FROM (VALUES (1)) AS t ("n")) UNION ALL (SELECT ("n" + 1) AS "n" FROM "t" AS "t" WHERE ("n" < 100))) SELECT sum(ALL "n") AS "getSum" FROM "t" AS "t"
```

It's not done yet because the first pair of parens need to surround the list of return fields and right now it's empty. That info is available at the type level but I need to figure how to get it to the term level with a type class or some type family magic.
